import { createContext, useContext, useState, type ReactNode } from 'react';

export type Lang = 'es' | 'en' | 'fi' | 'et' | 'sv';

const T: Record<Lang, Record<string, string>> = {
  es: {
    'sec.main': 'Principal', 'sec.prospecting': 'Prospección',
    'sec.ops': 'Operativa', 'sec.analytics': 'Análisis',
    'nav.dashboard': 'Dashboard', 'nav.pipeline': 'Pipeline',
    'nav.leads': 'Leads', 'nav.accounts': 'Cuentas',
    'nav.tasks': 'Tareas', 'nav.activities': 'Actividades', 'nav.reports': 'Informes',
    'btn.newLead': '+ Nuevo Lead', 'btn.newAccount': '+ Nueva Cuenta',
    'btn.export': 'Exportar CSV', 'btn.signin': 'Entrar',
    'btn.save': 'Guardar', 'btn.cancel': 'Cancelar',
    'filter.allZones': 'Todas las zonas', 'filter.allPlans': 'Todos los planes',
    'filter.allSources': 'Todas las fuentes', 'filter.allStatuses': 'Todos los estados',
    'filter.allAgents': 'Todos los agentes',
    'label.zone': 'Zona', 'label.plan': 'Plan', 'label.stage': 'Etapa',
    'label.agent': 'Agente', 'label.date': 'Fecha', 'label.status': 'Estado',
    'label.priority': 'Prioridad', 'label.name': 'Nombre', 'label.type': 'Tipo',
    'label.source': 'Fuente', 'label.mrr': 'MRR', 'label.contact': 'Contacto',
    'label.notes': 'Notas',
    'dash.activeLeads': 'Leads activos', 'dash.activeAccounts': 'Cuentas activas',
    'dash.mrr': 'MRR estimado', 'dash.overdue': 'Tareas vencidas',
    'dash.recentActivity': 'Actividad reciente', 'dash.priorityTasks': 'Tareas prioritarias',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'Ver todo →', 'common.today': 'Hoy',
    'common.thisWeek': 'Esta semana', 'common.thisMonth': 'Este mes',
    'common.search': 'Buscar...', 'common.loading': 'Cargando...',
    'stage.new': 'Nuevo', 'stage.attempting_contact': 'Contactando',
    'stage.contacted': 'Contactado', 'stage.interested': 'Interesado',
    'stage.demo_scheduled': 'Demo agendada', 'stage.proposal_sent': 'Propuesta enviada',
    'stage.negotiation': 'Negociación', 'stage.onboarding_pending': 'Onboarding',
    'stage.payment_pending': 'Pago pendiente', 'stage.active': 'Activo',
    'stage.at_risk': 'En riesgo', 'stage.churned': 'Churned', 'stage.lost': 'Perdido',
    'plan.premium_local': 'Premium Local', 'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotel Analytics', 'plan.hotel_elite': 'Hotel Elite',
    'priority.urgent': 'Urgente', 'priority.high': 'Alta',
    'priority.medium': 'Media', 'priority.low': 'Baja',
    'activity.call': 'Llamada', 'activity.email': 'Email',
    'activity.visit': 'Visita', 'activity.note': 'Nota', 'activity.system': 'Sistema',
    'reports.title': 'Informes', 'reports.download': 'Descargar',
    'reports.type': 'Tipo de informe', 'reports.period': 'Período',
    'reports.today': 'Hoy', 'reports.week': 'Esta semana',
    'reports.month': 'Este mes', 'reports.quarter': 'Trimestre',
    'reports.year': 'Este año', 'reports.custom': '📅 Personalizado',
    'reports.pdf': '⬇ PDF', 'reports.excel': '⬇ Excel',
    'report.executive': '📋 Resumen ejecutivo', 'report.pipeline': '⬡ Pipeline y conversión',
    'report.activity': '↺ Actividad comercial', 'report.leads': '◎ Leads y prospección',
    'report.billing': '€ Facturación y MRR', 'report.agents': '👤 Rendimiento por agente',
    'lead.new': 'Nuevo Lead', 'lead.name': 'Nombre del local / hotel',
    'lead.phone': 'Teléfono de contacto',
    'ops.loading': 'Cargando...', 'ops.title': 'Dashboard OPS',
    'ops.allTime': 'Todo', 'ops.thisMonth': 'Este mes',
    'ops.lastMonth': 'Mes anterior', 'ops.thisYear': 'Este año',
    'ops.resetData': 'Reset datos', 'ops.collected': 'Cobrado',
    'ops.outstanding': 'Pendiente', 'ops.cashBalance': 'Saldo caja',
    'ops.forecast': 'Previsión 30d', 'ops.overdueInvoices': 'Facturas vencidas',
    'ops.daysOverdue': 'd vencidos', 'ops.vatReport': 'Informe IVA',
    'ops.outputVat': 'IVA repercutido', 'ops.inputVat': 'IVA soportado',
    'ops.netVat': 'IVA neto a ingresar', 'ops.recentCash': 'Últimos movimientos',
    'ops.noMovements': 'Sin movimientos', 'ops.latestInvoices': 'Últimas facturas',
    'ops.noInvoices': 'Sin facturas', 'ops.invoiceNumber': 'Número',
    'ops.invoiceDue': 'Vencimiento', 'ops.clientName': 'Cliente',
    'ops.date': 'Fecha', 'ops.total': 'Total', 'ops.status': 'Estado',
    'ops.nav.section': 'OPS — Finanzas', 'ops.nav.dashboard': 'Dashboard OPS',
    'ops.nav.invoices': 'Facturas', 'ops.nav.cash': 'Caja',
    'ops.nav.timelog': 'Control Horario', 'ops.nav.clients': 'Clientes OPS',
    'ops.nav.visits': 'Visitas', 'ops.nav.venues': 'Locales', 'ops.nav.ai': 'Asistente IA OPS',
    'venues.title': 'Locales (Costa del Sol)',
    'venues.subtitle': 'locales en el sistema — prospects para comercial',
    'venues.searchPh': 'Buscar por nombre o dirección…',
    'venues.allCategories': 'Todas las categorías',
    'venues.unclaimed': 'Sin reclamar',
    'venues.unvisited': 'Sin visitar',
    'venues.category': 'Categoría',
    'venues.premium': 'Premium',
    'venues.claimed': 'Reclamado',
    'venues.cold': 'Frío',
    'venues.prev': 'Anterior',
    'venues.next': 'Siguiente',
    'venues.page': 'Página',
    'venues.of': 'de',
    'venues.empty': 'Sin resultados',
  },
  en: {
    'sec.main': 'Main', 'sec.prospecting': 'Prospecting',
    'sec.ops': 'Operations', 'sec.analytics': 'Analytics',
    'nav.dashboard': 'Dashboard', 'nav.pipeline': 'Pipeline',
    'nav.leads': 'Leads', 'nav.accounts': 'Accounts',
    'nav.tasks': 'Tasks', 'nav.activities': 'Activity', 'nav.reports': 'Reports',
    'btn.newLead': '+ New Lead', 'btn.newAccount': '+ New Account',
    'btn.export': 'Export CSV', 'btn.signin': 'Sign In',
    'btn.save': 'Save', 'btn.cancel': 'Cancel',
    'filter.allZones': 'All zones', 'filter.allPlans': 'All plans',
    'filter.allSources': 'All sources', 'filter.allStatuses': 'All statuses',
    'filter.allAgents': 'All agents',
    'label.zone': 'Zone', 'label.plan': 'Plan', 'label.stage': 'Stage',
    'label.agent': 'Agent', 'label.date': 'Date', 'label.status': 'Status',
    'label.priority': 'Priority', 'label.name': 'Name', 'label.type': 'Type',
    'label.source': 'Source', 'label.mrr': 'MRR', 'label.contact': 'Contact',
    'label.notes': 'Notes',
    'dash.activeLeads': 'Active Leads', 'dash.activeAccounts': 'Active Accounts',
    'dash.mrr': 'Estimated MRR', 'dash.overdue': 'Overdue Tasks',
    'dash.recentActivity': 'Recent Activity', 'dash.priorityTasks': 'Priority Tasks',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'See all →', 'common.today': 'Today',
    'common.thisWeek': 'This week', 'common.thisMonth': 'This month',
    'common.search': 'Search...', 'common.loading': 'Loading...',
    'stage.new': 'New', 'stage.attempting_contact': 'Attempting contact',
    'stage.contacted': 'Contacted', 'stage.interested': 'Interested',
    'stage.demo_scheduled': 'Demo scheduled', 'stage.proposal_sent': 'Proposal sent',
    'stage.negotiation': 'Negotiation', 'stage.onboarding_pending': 'Onboarding',
    'stage.payment_pending': 'Payment pending', 'stage.active': 'Active',
    'stage.at_risk': 'At risk', 'stage.churned': 'Churned', 'stage.lost': 'Lost',
    'plan.premium_local': 'Premium Local', 'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotel Analytics', 'plan.hotel_elite': 'Hotel Elite',
    'priority.urgent': 'Urgent', 'priority.high': 'High',
    'priority.medium': 'Medium', 'priority.low': 'Low',
    'activity.call': 'Call', 'activity.email': 'Email',
    'activity.visit': 'Visit', 'activity.note': 'Note', 'activity.system': 'System',
    'reports.title': 'Reports', 'reports.download': 'Download',
    'reports.type': 'Report type', 'reports.period': 'Period',
    'reports.today': 'Today', 'reports.week': 'This week',
    'reports.month': 'This month', 'reports.quarter': 'Quarter',
    'reports.year': 'This year', 'reports.custom': '📅 Custom',
    'reports.pdf': '⬇ PDF', 'reports.excel': '⬇ Excel',
    'report.executive': '📋 Executive summary', 'report.pipeline': '⬡ Pipeline & conversion',
    'report.activity': '↺ Commercial activity', 'report.leads': '◎ Leads & prospecting',
    'report.billing': '€ Billing & MRR', 'report.agents': '👤 Agent performance',
    'lead.new': 'New Lead', 'lead.name': 'Venue / hotel name',
    'lead.phone': 'Contact phone',
    'ops.loading': 'Loading...', 'ops.title': 'OPS Dashboard',
    'ops.allTime': 'All time', 'ops.thisMonth': 'This month',
    'ops.lastMonth': 'Last month', 'ops.thisYear': 'This year',
    'ops.resetData': 'Reset data', 'ops.collected': 'Collected',
    'ops.outstanding': 'Outstanding', 'ops.cashBalance': 'Cash balance',
    'ops.forecast': '30-day forecast', 'ops.overdueInvoices': 'Overdue invoices',
    'ops.daysOverdue': 'd overdue', 'ops.vatReport': 'VAT report',
    'ops.outputVat': 'Output VAT', 'ops.inputVat': 'Input VAT',
    'ops.netVat': 'Net VAT payable', 'ops.recentCash': 'Recent movements',
    'ops.noMovements': 'No movements', 'ops.latestInvoices': 'Latest invoices',
    'ops.noInvoices': 'No invoices', 'ops.invoiceNumber': 'Number',
    'ops.invoiceDue': 'Due date', 'ops.clientName': 'Client',
    'ops.date': 'Date', 'ops.total': 'Total', 'ops.status': 'Status',
    'ops.nav.section': 'OPS — Finance', 'ops.nav.dashboard': 'OPS Dashboard',
    'ops.nav.invoices': 'Invoices', 'ops.nav.cash': 'Cash',
    'ops.nav.timelog': 'Time Log', 'ops.nav.clients': 'OPS Clients',
    'ops.nav.visits': 'Visits', 'ops.nav.venues': 'Venues', 'ops.nav.ai': 'AI Assistant OPS',
    'venues.title': 'Venues (Costa del Sol)',
    'venues.subtitle': 'venues in the system — commercial prospects',
    'venues.searchPh': 'Search by name or address…',
    'venues.allCategories': 'All categories',
    'venues.unclaimed': 'Unclaimed',
    'venues.unvisited': 'Not yet visited',
    'venues.category': 'Category',
    'venues.premium': 'Premium',
    'venues.claimed': 'Claimed',
    'venues.cold': 'Cold',
    'venues.prev': 'Previous',
    'venues.next': 'Next',
    'venues.page': 'Page',
    'venues.of': 'of',
    'venues.empty': 'No results',
  },
  fi: {
    'sec.main': 'Etusivu',
    'sec.prospecting': 'Etsintä',
    'sec.ops': 'Operatiivinen',
    'sec.analytics': 'Analyysi',
    'nav.dashboard': 'Kojelauta',
    'nav.pipeline': 'Putkisto',
    'nav.leads': 'Liidit',
    'nav.accounts': 'Tilit',
    'nav.tasks': 'Tehtävät',
    'nav.activities': 'Toiminta',
    'nav.reports': 'Raportit',
    'btn.newLead': '+ Uusi liidi',
    'btn.newAccount': '+ Uusi tili',
    'btn.export': 'Vie CSV-tiedosto',
    'btn.signin': 'Kirjaudu sisään',
    'btn.save': 'Tallenna',
    'btn.cancel': 'Peruuta',
    'filter.allZones': 'Kaikki alueet',
    'filter.allPlans': 'Kaikki paketit',
    'filter.allSources': 'Kaikki lähteet',
    'filter.allStatuses': 'Kaikki osavaltiot',
    'filter.allAgents': 'Kaikki toimijat',
    'label.zone': 'Alue',
    'label.plan': 'Suunnitelma',
    'label.stage': 'Vaihe',
    'label.agent': 'Agentti',
    'label.date': 'Päivämäärä',
    'label.status': 'Tila',
    'label.priority': 'Prioriteetti',
    'label.name': 'Nimi',
    'label.type': 'Tyyppi',
    'label.source': 'Lähde',
    'label.mrr': 'MRR',
    'label.contact': 'Yhteystiedot',
    'label.notes': 'Huomautukset',
    'dash.activeLeads': 'Aktiiviset liidit',
    'dash.activeAccounts': 'Aktiiviset tilit',
    'dash.mrr': 'Arvioitu MRR',
    'dash.overdue': 'Erääntyneet tehtävät',
    'dash.recentActivity': 'Viimeaikaiset toimet',
    'dash.priorityTasks': 'Ensisijaiset tehtävät',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'Näytä kaikki →',
    'common.today': 'Tänään',
    'common.thisWeek': 'Tällä viikolla',
    'common.thisMonth': 'Tässä kuussa',
    'common.search': 'Hae...',
    'common.loading': 'Ladataan...',
    'stage.new': 'Uusi',
    'stage.attempting_contact': 'Yhteydenotto',
    'stage.contacted': 'Otettu yhteyttä',
    'stage.interested': 'Kiinnostunut',
    'stage.demo_scheduled': 'Demo on sovittu',
    'stage.proposal_sent': 'Ehdotus lähetetty',
    'stage.negotiation': 'Neuvottelu',
    'stage.onboarding_pending': 'Työhön perehdyttäminen',
    'stage.payment_pending': 'Maksu odottaa suoritusta',
    'stage.active': 'Aktiivinen',
    'stage.at_risk': 'Vaarassa',
    'stage.churned': 'Churned',
    'stage.lost': 'Kadonnut',
    'plan.premium_local': 'Premium Local',
    'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotellianalytiikka',
    'plan.hotel_elite': 'Elite-hotelli',
    'priority.urgent': 'Kiireellinen',
    'priority.high': 'Ilmoittautuminen',
    'priority.medium': 'Media',
    'priority.low': 'Poista',
    'activity.call': 'Puhelu',
    'activity.email': 'Sähköposti',
    'activity.visit': 'Vierailu',
    'activity.note': 'Huomautus',
    'activity.system': 'Järjestelmä',
    'reports.title': 'Raportit',
    'reports.download': 'Lataa',
    'reports.type': 'Raportin tyyppi',
    'reports.period': 'Ajanjakso',
    'reports.today': 'Tänään',
    'reports.week': 'Tällä viikolla',
    'reports.month': 'Tässä kuussa',
    'reports.quarter': 'Neljännesvuosi',
    'reports.year': 'Tänä vuonna',
    'reports.custom': '📅 Räätälöity',
    'reports.pdf': '⬇ PDF',
    'reports.excel': '⬇ Excel',
    'report.executive': '📋 Tiivistelmä',
    'report.pipeline': '⬡ Myyntiputki ja konversio',
    'report.activity': '↺ Liiketoiminta',
    'report.leads': '◎ Liidit ja prospektointi',
    'report.billing': '€ Liikevaihto ja MRR',
    'report.agents': '👤 Suorituskyky agenttikohtaisesti',
    'lead.new': 'Uusi liidi',
    'lead.name': 'Ravintolan / hotellin nimi',
    'lead.phone': 'Yhteysnumero',
    'ops.loading': 'Ladataan...',
    'ops.title': 'OPS-hallintapaneeli',
    'ops.allTime': 'Kaikki',
    'ops.thisMonth': 'Tässä kuussa',
    'ops.lastMonth': 'Edellinen kuukausi',
    'ops.thisYear': 'Tänä vuonna',
    'ops.resetData': 'Tietojen nollaus',
    'ops.collected': 'Peritty',
    'ops.outstanding': 'Käsiteltävänä',
    'ops.cashBalance': 'Kassan saldo',
    'ops.forecast': '30 päivän ennuste',
    'ops.overdueInvoices': 'Erääntyneet laskut',
    'ops.daysOverdue': 'erääntyneet',
    'ops.vatReport': 'Arvonlisäveroraportti',
    'ops.outputVat': 'laskutettu arvonlisävero',
    'ops.inputVat': 'maksettu arvonlisävero',
    'ops.netVat': 'Maksettava netto-arvonlisävero',
    'ops.recentCash': 'Viimeisimmät muutokset',
    'ops.noMovements': 'Ei liikkeitä',
    'ops.latestInvoices': 'Viimeisimmät laskut',
    'ops.noInvoices': 'Ilman laskuja',
    'ops.invoiceNumber': 'Numero',
    'ops.invoiceDue': 'Eräpäivä',
    'ops.clientName': 'Asiakas',
    'ops.date': 'Päivämäärä',
    'ops.total': 'Yhteensä',
    'ops.status': 'Tila',
    'ops.nav.section': 'OPS — Talous',
    'ops.nav.dashboard': 'OPS-hallintapaneeli',
    'ops.nav.invoices': 'Laskut',
    'ops.nav.cash': 'Laatikko',
    'ops.nav.timelog': 'Työajan seuranta',
    'ops.nav.clients': 'OPS-asiakkaat',
    'ops.nav.visits': 'Vierailut',
    'ops.nav.venues': 'Paikalliset',
    'ops.nav.ai': 'OPS-tekoälyavustaja',
    'venues.title': 'Toimipisteet (Costa del Sol)',
    'venues.subtitle': 'toimipistettä järjestelmässä — myyntikohteet',
    'venues.searchPh': 'Hae nimen tai osoitteen perusteella…',
    'venues.allCategories': 'Kaikki kategoriat',
    'venues.unclaimed': 'Vaatimatta',
    'venues.unvisited': 'Käymättä',
    'venues.category': 'Luokka',
    'venues.premium': 'Premium',
    'venues.claimed': 'Vaadittu',
    'venues.cold': 'Kylmä',
    'venues.prev': 'Edellinen',
    'venues.next': 'Seuraava',
    'venues.page': 'Sivu',
    'venues.of': '/',
    'venues.empty': 'Ei tuloksia',
  },
  et: {
    'sec.main': 'Avaleht',
    'sec.prospecting': 'Uurimistöö',
    'sec.ops': 'Operatiivne',
    'sec.analytics': 'Analüüs',
    'nav.dashboard': 'Juhtpaneel',
    'nav.pipeline': 'Torujuhe',
    'nav.leads': 'Potentsiaalsed kliendid',
    'nav.accounts': 'Arved',
    'nav.tasks': 'Ülesanded',
    'nav.activities': 'Tegevused',
    'nav.reports': 'Aruanded',
    'btn.newLead': '+ Uus potentsiaalne klient',
    'btn.newAccount': '+ Uus konto',
    'btn.export': 'CSV-faili eksportimine',
    'btn.signin': 'Sisse logida',
    'btn.save': 'Salvesta',
    'btn.cancel': 'Tühista',
    'filter.allZones': 'Kõik piirkonnad',
    'filter.allPlans': 'Kõik paketid',
    'filter.allSources': 'Kõik allikad',
    'filter.allStatuses': 'Kõik osariigid',
    'filter.allAgents': 'Kõik esindajad',
    'label.zone': 'Piirkond',
    'label.plan': 'Kava',
    'label.stage': 'Etapp',
    'label.agent': 'Agent',
    'label.date': 'Kuupäev',
    'label.status': 'Seisund',
    'label.priority': 'Prioriteet',
    'label.name': 'Nimi',
    'label.type': 'Tüüp',
    'label.source': 'Allikas',
    'label.mrr': 'MRR',
    'label.contact': 'Kontakt',
    'label.notes': 'Märkused',
    'dash.activeLeads': 'Aktiivsed potentsiaalsed kliendid',
    'dash.activeAccounts': 'Aktiivsed kontod',
    'dash.mrr': 'Hinnanguline MRR',
    'dash.overdue': 'Tähtaeg ületanud ülesanded',
    'dash.recentActivity': 'Viimased tegevused',
    'dash.priorityTasks': 'Esmatähtsad ülesanded',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'Vaata kõiki →',
    'common.today': 'Täna',
    'common.thisWeek': 'Sel nädalal',
    'common.thisMonth': 'Sel kuul',
    'common.search': 'Otsi...',
    'common.loading': 'Laadimine...',
    'stage.new': 'Uus',
    'stage.attempting_contact': 'Kontakt',
    'stage.contacted': 'Võeti ühendust',
    'stage.interested': 'Huvitatud',
    'stage.demo_scheduled': 'Demo on kavandatud',
    'stage.proposal_sent': 'Ettepanek on saadetud',
    'stage.negotiation': 'Läbirääkimised',
    'stage.onboarding_pending': 'Uute töötajate sisseelamine',
    'stage.payment_pending': 'Makse on veel tasumata',
    'stage.active': 'Aktiiv',
    'stage.at_risk': 'Ohustatud',
    'stage.churned': 'Churned',
    'stage.lost': 'Kadunud',
    'plan.premium_local': 'Premium Local',
    'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotellianalüütika',
    'plan.hotel_elite': 'Hotell Elite',
    'priority.urgent': 'Kiire',
    'priority.high': 'Registreerimine',
    'priority.medium': 'Keskmine',
    'priority.low': 'Alla',
    'activity.call': 'Kõne',
    'activity.email': 'E-post',
    'activity.visit': 'Külastus',
    'activity.note': 'Märkus',
    'activity.system': 'Süsteem',
    'reports.title': 'Aruanded',
    'reports.download': 'Alla laadida',
    'reports.type': 'Aruande liik',
    'reports.period': 'Ajavahemik',
    'reports.today': 'Täna',
    'reports.week': 'Sel nädalal',
    'reports.month': 'Sel kuul',
    'reports.quarter': 'Kvartal',
    'reports.year': 'Sel aastal',
    'reports.custom': '📅 Isikupärastatud',
    'reports.pdf': '⬇ PDF',
    'reports.excel': '⬇ Excel',
    'report.executive': '📋 Kokkuvõte',
    'report.pipeline': '⬡ Müügitoru ja konversioon',
    'report.activity': '↺ Äritegevus',
    'report.leads': '◎ Potentsiaalsed kliendid ja potentsiaalsete klientide otsimine',
    'report.billing': '€ Käive ja MRR',
    'report.agents': '👤 Tulemuslikkus töötaja kohta',
    'lead.new': 'Uus potentsiaalne klient',
    'lead.name': 'Asutuse / hotelli nimi',
    'lead.phone': 'Kontaktnumber',
    'ops.loading': 'Laadimine...',
    'ops.title': 'OPS-i juhtpaneel',
    'ops.allTime': 'Kõik',
    'ops.thisMonth': 'Sel kuul',
    'ops.lastMonth': 'Eelmine kuu',
    'ops.thisYear': 'Sel aastal',
    'ops.resetData': 'Andmete tühistamine',
    'ops.collected': 'Laekunud',
    'ops.outstanding': 'Ootel',
    'ops.cashBalance': 'Kassasaldo',
    'ops.forecast': '30-päevane prognoos',
    'ops.overdueInvoices': 'Tähtaegunud arved',
    'ops.daysOverdue': 'tähtaeg ületanud',
    'ops.vatReport': 'Käibemaksuaruanne',
    'ops.outputVat': 'Edasi arvestatud käibemaks',
    'ops.inputVat': 'Eelnevalt tasutud käibemaks',
    'ops.netVat': 'Tasumisele kuuluv neto-käibemaks',
    'ops.recentCash': 'Viimased muutused',
    'ops.noMovements': 'Liikumisteta',
    'ops.latestInvoices': 'Viimased arved',
    'ops.noInvoices': 'Ilma arveteta',
    'ops.invoiceNumber': 'Number',
    'ops.invoiceDue': 'Tähtaeg',
    'ops.clientName': 'Klient',
    'ops.date': 'Kuupäev',
    'ops.total': 'Kokku',
    'ops.status': 'Seisund',
    'ops.nav.section': 'OPS — Rahandus',
    'ops.nav.dashboard': 'OPS-i juhtpaneel',
    'ops.nav.invoices': 'Arved',
    'ops.nav.cash': 'Kast',
    'ops.nav.timelog': 'Tööaja arvestus',
    'ops.nav.clients': 'OPS-i kliendid',
    'ops.nav.visits': 'Külastused',
    'ops.nav.venues': 'Kohalikud',
    'ops.nav.ai': 'OPS-i tehisintellekti abiline',
    'venues.title': 'Ettevõtted (Costa del Sol)',
    'venues.subtitle': 'ettevõtet süsteemis — potentsiaalsed kliendid',
    'venues.searchPh': 'Otsi nime või aadressi järgi…',
    'venues.allCategories': 'Kõik kategooriad',
    'venues.unclaimed': 'Nõudeta',
    'venues.unvisited': 'Külastamata',
    'venues.category': 'Kategooria',
    'venues.premium': 'Premium',
    'venues.claimed': 'Nõutud',
    'venues.cold': 'Külm',
    'venues.prev': 'Eelmine',
    'venues.next': 'Järgmine',
    'venues.page': 'Lehekülg',
    'venues.of': '/',
    'venues.empty': 'Tulemusi ei leitud',
  },
  sv: {
    'sec.main': 'Huvudsida',
    'sec.prospecting': 'Prospektering',
    'sec.ops': 'Operativ verksamhet',
    'sec.analytics': 'Analys',
    'nav.dashboard': 'Instrumentpanelen',
    'nav.pipeline': 'Pipeline',
    'nav.leads': 'Leads',
    'nav.accounts': 'Konton',
    'nav.tasks': 'Uppgifter',
    'nav.activities': 'Aktiviteter',
    'nav.reports': 'Rapporter',
    'btn.newLead': '+ Ny lead',
    'btn.newAccount': '+ Nytt konto',
    'btn.export': 'Exportera CSV',
    'btn.signin': 'Logga in',
    'btn.save': 'Spara',
    'btn.cancel': 'Avbryt',
    'filter.allZones': 'Alla områden',
    'filter.allPlans': 'Alla abonnemang',
    'filter.allSources': 'Alla källor',
    'filter.allStatuses': 'Alla delstater',
    'filter.allAgents': 'Alla agenter',
    'label.zone': 'Område',
    'label.plan': 'Plan',
    'label.stage': 'Etapp',
    'label.agent': 'Agent',
    'label.date': 'Datum',
    'label.status': 'Status',
    'label.priority': 'Prioritet',
    'label.name': 'Namn',
    'label.type': 'Typ',
    'label.source': 'Källa',
    'label.mrr': 'MRR',
    'label.contact': 'Kontakt',
    'label.notes': 'Anmärkningar',
    'dash.activeLeads': 'Aktiva leads',
    'dash.activeAccounts': 'Aktiva konton',
    'dash.mrr': 'Uppskattad MRR',
    'dash.overdue': 'Förfallna uppgifter',
    'dash.recentActivity': 'Senaste aktivitet',
    'dash.priorityTasks': 'Prioriterade uppgifter',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'Visa allt →',
    'common.today': 'Idag',
    'common.thisWeek': 'Den här veckan',
    'common.thisMonth': 'Den här månaden',
    'common.search': 'Sök...',
    'common.loading': 'Laddar...',
    'stage.new': 'Nytt',
    'stage.attempting_contact': 'Kontakta oss',
    'stage.contacted': 'Kontaktad',
    'stage.interested': 'Intresserad',
    'stage.demo_scheduled': 'Planerad demonstration',
    'stage.proposal_sent': 'Förslaget har skickats',
    'stage.negotiation': 'Förhandling',
    'stage.onboarding_pending': 'Introduktion',
    'stage.payment_pending': 'Utestående betalning',
    'stage.active': 'Tillgång',
    'stage.at_risk': 'I riskzonen',
    'stage.churned': 'Churned',
    'stage.lost': 'Försvunnen',
    'plan.premium_local': 'Premium Lokalt',
    'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotellanalys',
    'plan.hotel_elite': 'Hotel Elite',
    'priority.urgent': 'Brådskande',
    'priority.high': 'Registrering',
    'priority.medium': 'Media',
    'priority.low': 'Ned',
    'activity.call': 'Samtal',
    'activity.email': 'E-post',
    'activity.visit': 'Besök',
    'activity.note': 'Anmärkning',
    'activity.system': 'System',
    'reports.title': 'Rapporter',
    'reports.download': 'Ladda ner',
    'reports.type': 'Rapporttyp',
    'reports.period': 'Period',
    'reports.today': 'Idag',
    'reports.week': 'Den här veckan',
    'reports.month': 'Den här månaden',
    'reports.quarter': 'Kvartal',
    'reports.year': 'I år',
    'reports.custom': '📅 Anpassad',
    'reports.pdf': '⬇ PDF',
    'reports.excel': '⬇ Excel',
    'report.executive': '📋 Sammanfattning',
    'report.pipeline': '⬡ Pipeline och konvertering',
    'report.activity': '↺ Affärsverksamhet',
    'report.leads': '◎ Leads och prospektering',
    'report.billing': '€ Omsättning och MRR',
    'report.agents': '👤 Resultat per agent',
    'lead.new': 'Ny lead',
    'lead.name': 'Namn på lokalen/hotellet',
    'lead.phone': 'Kontaktnummer',
    'ops.loading': 'Laddar...',
    'ops.title': 'OPS-instrumentpanelen',
    'ops.allTime': 'Allt',
    'ops.thisMonth': 'Den här månaden',
    'ops.lastMonth': 'Föregående månad',
    'ops.thisYear': 'I år',
    'ops.resetData': 'Återställ data',
    'ops.collected': 'Inkasserat',
    'ops.outstanding': 'Väntar på svar',
    'ops.cashBalance': 'Kassasaldo',
    'ops.forecast': '30-dagarsprognos',
    'ops.overdueInvoices': 'Förfallna fakturor',
    'ops.daysOverdue': 'förfallna',
    'ops.vatReport': 'Momsrapport',
    'ops.outputVat': 'Debiterad moms',
    'ops.inputVat': 'Ingående moms',
    'ops.netVat': 'Netto-moms att betala',
    'ops.recentCash': 'Senaste händelserna',
    'ops.noMovements': 'Inga rörelser',
    'ops.latestInvoices': 'Senaste fakturor',
    'ops.noInvoices': 'Utan fakturor',
    'ops.invoiceNumber': 'Nummer',
    'ops.invoiceDue': 'Förfallodag',
    'ops.clientName': 'Kund',
    'ops.date': 'Datum',
    'ops.total': 'Totalt',
    'ops.status': 'Status',
    'ops.nav.section': 'OPS — Ekonomi',
    'ops.nav.dashboard': 'OPS-instrumentpanelen',
    'ops.nav.invoices': 'Fakturor',
    'ops.nav.cash': 'Låda',
    'ops.nav.timelog': 'Tidsregistrering',
    'ops.nav.clients': 'OPS-kunder',
    'ops.nav.visits': 'Besök',
    'ops.nav.venues': 'Lokaler',
    'ops.nav.ai': 'AI-assistent för drift',
    'venues.title': 'Lokaler (Costa del Sol)',
    'venues.subtitle': 'lokaler i systemet — potentiella kunder',
    'venues.searchPh': 'Sök efter namn eller adress…',
    'venues.allCategories': 'Alla kategorier',
    'venues.unclaimed': 'Oanmälda',
    'venues.unvisited': 'Ej besökta',
    'venues.category': 'Kategori',
    'venues.premium': 'Premium',
    'venues.claimed': 'Anmäld',
    'venues.cold': 'Kall',
    'venues.prev': 'Föregående',
    'venues.next': 'Nästa',
    'venues.page': 'Sida',
    'venues.of': 'av',
    'venues.empty': 'Inga resultat',
  },

};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => (localStorage.getItem('crm_lang') as Lang) ?? 'es'
  );

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('crm_lang', l);
  };

  const t = (key: string): string => T[lang][key] ?? T.es[key] ?? key;

  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
}
