import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from 'react';

export type Lang = 'es' | 'en' | 'fi' | 'et';

const T: Record<Lang, Record<string, string>> = {
  es: {
    'sec.main': 'Principal', 'sec.prospecting': 'Prospección',
    'sec.ops': 'Operativa', 'sec.analytics': 'Análisis',
    'nav.dashboard': 'Dashboard', 'nav.pipeline': 'Pipeline',
    'nav.leads': 'Leads', 'nav.accounts': 'Cuentas',
    'nav.tasks': 'Tareas', 'nav.activities': 'Actividades', 'nav.reports': 'Informes',
    'nav.campaigns': 'Campañas',
    'btn.newLead': '+ Nuevo Lead', 'btn.newAccount': '+ Nueva Cuenta',
    'btn.export': 'Exportar CSV', 'btn.signin': 'Entrar',
    'btn.save': 'Guardar', 'btn.cancel': 'Cancelar',
    'btn.edit': 'Editar', 'common.yes': 'Sí', 'common.no': 'No',
    'filter.allZones': 'Todas las zonas', 'filter.allPlans': 'Todos los planes',
    'filter.allSources': 'Todas las fuentes', 'filter.allStatuses': 'Todos los estados',
    'filter.allAgents': 'Todos los agentes',
    'label.zone': 'Zona', 'label.plan': 'Plan', 'label.stage': 'Etapa',
    'label.agent': 'Agente', 'label.date': 'Fecha', 'label.status': 'Estado',
    'label.priority': 'Prioridad', 'label.name': 'Nombre', 'label.type': 'Tipo',
    'label.source': 'Fuente', 'label.mrr': 'MRR', 'label.contact': 'Contacto',
    'label.notes': 'Notas', 'label.address': 'Dirección',
    'common.back': 'Volver',
    'dash.activeLeads': 'Leads activos', 'dash.activeAccounts': 'Cuentas activas',
    'dash.mrr': 'MRR estimado', 'dash.overdue': 'Tareas vencidas',
    'dash.recentActivity': 'Actividad reciente', 'dash.priorityTasks': 'Tareas prioritarias',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'Ver todo →', 'common.today': 'Hoy',
    'common.thisWeek': 'Esta semana', 'common.thisMonth': 'Este mes',
    'common.search': 'Buscar...', 'common.loading': 'Cargando...',
    'common.email': 'Email', 'common.phone': 'Teléfono',
    'common.password': 'Contraseña', 'common.saving': 'Guardando...',
    'common.saveError': 'No se pudo guardar',
    'common.brandBadge': 'CRM Comercial', 'common.close': 'Cerrar',
    'common.menuOpen': 'Abrir menú', 'common.menuClose': 'Cerrar menú',
    'nav.assistant': 'Asistente IA',
    'auth.signOut': 'Cerrar sesión', 'role.superAdmin': 'Super Admin',
    'app.installTitle': 'Instalar app',
    'app.installInstructions': 'Instalar PulseCosta CRM\n\niOS Safari → Compartir → Añadir a pantalla de inicio\nAndroid/Chrome → Menú ⋮ → Instalar app\nChrome desktop → Menú ⋮ → Instalar app',
    'login.subtitle': 'CRM · Panel Comercial',
    'login.passwordRequired': 'Introduce tu contraseña',
    'login.invalidCredentials': 'Credenciales incorrectas',
    'login.showPassword': 'Mostrar contraseña',
    'login.hidePassword': 'Ocultar contraseña',
    'login.footer': 'Fuengirola · Marbella · Estepona · Costa del Sol',
    'placeholder.initialNotes': 'Notas iniciales...',
    'placeholder.contactName': 'Nombre del contacto',
    'placeholder.taskTitle': 'Llamar a Hotel Bahía',
    'placeholder.activityDescription': 'Describe la actividad...',
    'type.local': 'Local / Bar / Rest.',
    'type.hotel': 'Hotel',
    'lead.convertConfirm': '¿Convertir "{name}" en cuenta del pipeline?',
    'lead.convertError': 'No se pudo convertir',
    'lead.converting': 'Convirtiendo...',
    'lead.convertToAccount': 'Convertir en cuenta',
    'lead.call': 'Llamar',
    'lead.originNote': 'Origen: lead #{id}{source}',
    'assistant.summary': 'Resumen del día',
    'assistant.visits': 'Análisis de visitas',
    'assistant.ask': 'Preguntar',
    'assistant.subtitle': 'IA local (Spark) · PulseCosta CRM',
    'assistant.generate': 'Generar',
    'assistant.empty': 'Selecciona un modo y genera tu primer análisis.',
    'assistant.loading': 'Analizando con IA local (Spark)...',
    'assistant.questionPh': 'Pregunta algo sobre el CRM...',
    'assistant.send': 'Enviar',
    'assistant.clear': 'Limpiar conversación',
    'account.notFound': 'Cuenta no encontrada.',
    'account.overview': 'Resumen',
    'account.contractDetails': 'Detalles del contrato',
    'account.perMonth': 'mes',
    'account.perYear': 'año',
    'account.annualMrr': 'MRR anual',
    'account.createdAt': 'Alta',
    'account.updatedAt': 'Última actualización',
    'account.noActivity': 'Sin actividad registrada.',
    'account.tasksHelp': 'Las tareas asociadas a esta cuenta se gestionan desde la sección Tareas.',
    'label.companyName': 'Empresa / Nombre',
    'label.contactPerson': 'Persona de contacto',
    'label.postalCode': 'Código postal',
    'label.city': 'Ciudad',
    'label.country': 'País',
    'ops.clients.title': 'Clientes',
    'ops.clients.new': 'Nuevo cliente',
    'ops.clients.edit': 'Editar cliente',
    'ops.clients.save': 'Guardar cliente',
    'ops.clients.searchPh': 'Buscar por nombre, ciudad o NIF/CIF...',
    'ops.clients.empty': 'No se han encontrado clientes',
    'ops.clients.pending': 'Pendiente',
    'ops.clients.invoiceHistory': 'Historial de facturas',
    'ops.clients.visitHistory': 'Historial de visitas',
    'ops.clients.noVisits': 'Sin visitas',
    'ops.clients.addressPh': 'Calle y número',
    'visit.status.pending': 'Pendiente',
    'visit.status.follow_up': 'Seguimiento',
    'visit.status.closed': 'Cerrada',
    'visit.status.lost': 'Perdida',
    'ops.visits.title': 'CRM de visitas',
    'ops.visits.new': 'Nueva visita',
    'ops.visits.edit': 'Editar visita',
    'ops.visits.save': 'Guardar visita',
    'ops.visits.empty': 'No se han encontrado visitas',
    'ops.visits.all': 'Todas',
    'ops.visits.prospectSection': 'Prospecto / Empresa',
    'ops.visits.publicSearch': 'Buscar local en base pública (Costa del Sol)',
    'ops.visits.publicSearchPh': 'Escribe 2+ letras del nombre...',
    'ops.visits.publicSearchHelp': '¿No está en la base? Deja este campo vacío y rellena manualmente abajo (prospect libre).',
    'ops.visits.publicVenue': 'Local de base pública:',
    'ops.visits.changeVenue': 'Cambiar',
    'ops.visits.venueCompany': 'Local / Empresa',
    'ops.visits.detailsSection': 'Detalles de la visita',
    'ops.visits.existingClient': 'Cliente existente (opcional — solo para visitas de upsell)',
    'ops.visits.newProspect': '— Prospecto (nuevo) —',
    'ops.visits.clientSearchPh': 'Buscar cliente...',
    'ops.visits.selectPlan': 'Seleccionar plan...',
    'ops.visits.proposalSent': 'Propuesta enviada',
    'ops.visits.followUpDate': 'Fecha de seguimiento',
    'ops.visits.nextAction': 'Siguiente acción',
    'ops.visits.visitDate': 'Visita',
    'ops.visits.followUp': 'Seguimiento',
    'ops.visits.client': 'Cliente',
    'ops.visits.fieldTitle': 'Registrada en PulseField',
    'ops.visits.convertToClient': 'Convertir en cliente',
    'ops.visits.converting': 'Convirtiendo...',
    'ops.visits.convertError': 'No se pudo convertir en cliente',
    'ops.visits.clientCreated': 'Cliente "{name}" creado. Ve a Facturas para crear su primera factura.',
    'ops.cash.title': 'Caja',
    'ops.cash.income': 'Ingreso',
    'ops.cash.expense': 'Gasto',
    'ops.cash.newIncome': 'Nuevo ingreso',
    'ops.cash.newExpense': 'Nuevo gasto',
    'ops.cash.addIncome': 'Añadir ingreso',
    'ops.cash.addExpense': 'Añadir gasto',
    'ops.cash.concept': 'Concepto',
    'ops.cash.conceptIncomePh': 'p. ej. Suscripción mensual La Bahía',
    'ops.cash.conceptExpensePh': 'p. ej. Hosting VPS Hostinger',
    'ops.cash.amount': 'Importe',
    'ops.cash.category': 'Categoría',
    'ops.cash.select': 'Seleccionar...',
    'ops.cash.vatType': 'Tipo de IVA',
    'ops.cash.vatNormal': 'Normal (con IVA)',
    'ops.cash.vatReverse': 'Inversión del sujeto pasivo (UE B2B)',
    'ops.cash.vatExempt': 'Exento',
    'ops.cash.vatRate': 'Porcentaje de IVA (%)',
    'ops.cash.linkInvoice': 'Vincular a factura (opcional)',
    'ops.cash.linkClient': 'Cliente (opcional)',
    'ops.cash.noInvoice': 'Ninguna',
    'ops.cash.noClient': 'Ninguno',
    'ops.cash.invoiceSearchPh': 'Buscar factura...',
    'ops.cash.clientSearchPh': 'Buscar cliente...',
    'ops.cash.recurring': 'Recurrente',
    'ops.cash.monthly': 'Mensual',
    'ops.cash.quarterly': 'Trimestral',
    'ops.cash.totalIncome': 'Total ingresos',
    'ops.cash.totalExpenses': 'Total gastos',
    'ops.cash.noMovements': 'Aún no hay movimientos',
    'ops.cash.category.Invoice': 'Factura',
    'ops.cash.category.Subscription': 'Suscripción',
    'ops.cash.category.Grant': 'Subvención',
    'ops.cash.category.Server': 'Servidor',
    'ops.cash.category.Salary': 'Salarios',
    'ops.cash.category.Travel': 'Viajes',
    'ops.cash.category.Marketing': 'Marketing',
    'ops.cash.category.Legal': 'Legal',
    'ops.cash.category.Software': 'Software',
    'ops.cash.category.Office': 'Oficina',
    'ops.cash.category.Other': 'Otro',
    'stage.new': 'Nuevo', 'stage.attempting_contact': 'Contactando',
    'stage.contacted': 'Contactado', 'stage.interested': 'Interesado',
    'stage.demo_scheduled': 'Demo agendada', 'stage.proposal_sent': 'Propuesta enviada',
    'stage.negotiation': 'Negociación', 'stage.onboarding_pending': 'Onboarding',
    'stage.payment_pending': 'Pago pendiente', 'stage.active': 'Activo', 'stage.converted': 'Convertido',
    'stage.at_risk': 'En riesgo', 'stage.churned': 'Churned', 'stage.lost': 'Perdido',
    'plan.premium_local': 'Premium Local', 'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotel Analytics', 'plan.hotel_elite': 'Hotel Elite',
    'priority.urgent': 'Urgente', 'priority.high': 'Alta',
    'priority.medium': 'Media', 'priority.low': 'Baja',
    'activity.call': 'Llamada', 'activity.email': 'Email',
    'activity.visit': 'Visita', 'activity.note': 'Nota', 'activity.system': 'Sistema',
    'reports.title': 'Informes', 'reports.download': 'Descargar',
    'reports.type': 'Tipo de informe', 'reports.period': 'Período',
    'reports.today': 'Hoy', 'reports.week': 'Esta semana',
    'reports.month': 'Este mes', 'reports.quarter': 'Trimestre',
    'reports.year': 'Este año', 'reports.custom': '📅 Personalizado',
    'reports.pdf': '⬇ PDF', 'reports.excel': '⬇ Excel',
    'report.executive': '📋 Resumen ejecutivo', 'report.pipeline': '⬡ Pipeline y conversión',
    'report.activity': '↺ Actividad comercial', 'report.leads': '◎ Leads y prospección',
    'report.billing': '€ Facturación y MRR', 'report.agents': '👤 Rendimiento por agente',
    'lead.new': 'Nuevo Lead', 'lead.name': 'Nombre del local / hotel',
    'lead.phone': 'Teléfono de contacto',
    'ops.loading': 'Cargando...', 'ops.title': 'Dashboard OPS',
    'ops.allTime': 'Todo', 'ops.thisMonth': 'Este mes',
    'ops.lastMonth': 'Mes anterior', 'ops.thisYear': 'Este año',
    'ops.resetData': 'Reset datos', 'ops.collected': 'Cobrado',
    'ops.outstanding': 'Pendiente', 'ops.cashBalance': 'Saldo caja',
    'ops.forecast': 'Previsión 30d', 'ops.overdueInvoices': 'Facturas vencidas',
    'ops.daysOverdue': 'd vencidos', 'ops.vatReport': 'Informe IVA',
    'ops.outputVat': 'IVA repercutido', 'ops.inputVat': 'IVA soportado',
    'ops.netVat': 'IVA neto a ingresar', 'ops.recentCash': 'Últimos movimientos',
    'ops.noMovements': 'Sin movimientos', 'ops.latestInvoices': 'Últimas facturas',
    'ops.noInvoices': 'Sin facturas', 'ops.invoiceNumber': 'Número',
    'ops.invoiceDue': 'Vencimiento', 'ops.clientName': 'Cliente',
    'ops.date': 'Fecha', 'ops.total': 'Total', 'ops.status': 'Estado',
    'invoice.new': 'Nueva factura',
    'invoice.create': 'Crear factura',
    'invoice.number': 'Número de factura',
    'invoice.selectClient': 'Selecciona cliente…',
    'invoice.searchClient': 'Buscar cliente…',
    'invoice.issueDate': 'Fecha de emisión',
    'invoice.dueDate': 'Fecha de vencimiento',
    'invoice.dueShort': 'Vence',
    'invoice.paymentMethod': 'Método de pago',
    'invoice.payment.bankTransfer': 'Transferencia',
    'invoice.payment.cash': 'Efectivo',
    'invoice.type.normal': 'Normal',
    'invoice.type.recurring': 'Recurrente',
    'invoice.interval': 'Intervalo',
    'invoice.interval.monthly': 'Mensual',
    'invoice.interval.quarterly': 'Trimestral',
    'invoice.vatJurisdiction': 'Jurisdicción de IVA',
    'invoice.vatRateFor': 'Tasa de IVA · {jurisdiction} (%)',
    'invoice.jurisdiction.estonia': 'Estonia',
    'invoice.jurisdiction.spain': 'España',
    'invoice.jurisdiction.eu': 'UE',
    'invoice.jurisdiction.exento': 'Exento',
    'invoice.reverseTitle': 'Inversión del sujeto pasivo (Art. 44)',
    'invoice.reverseHelp': 'IVA = 0%. Se requiere el número VAT del cliente. La nota legal aparecerá en el PDF.',
    'invoice.missingVatWarning': 'Este cliente no tiene VAT. Añádelo en Clientes antes de emitir la factura.',
    'invoice.lines': 'Líneas',
    'invoice.description': 'Descripción',
    'invoice.qty': 'Cant.',
    'invoice.unitPrice': 'Precio unit.',
    'invoice.amount': 'Importe',
    'invoice.serviceDescription': 'Descripción del servicio',
    'invoice.addLine': '+ Añadir línea',
    'invoice.taxableBase': 'Base imponible',
    'invoice.vatType': 'Tipo IVA',
    'invoice.vat.normal': 'IVA',
    'invoice.vat.normalRate': 'IVA {rate}%',
    'invoice.vat.reverseShort': 'Inversión SP',
    'invoice.vat.exempt': 'Exento',
    'invoice.notesPh': 'Notas internas o información adicional',
    'invoice.error.selectClient': 'Selecciona un cliente',
    'invoice.detailTitle': 'Factura {number}',
    'invoice.issueDue': 'Emisión / Vencimiento',
    'invoice.noDueDate': 'Sin vencimiento',
    'invoice.paymentLink': 'Enlace de pago',
    'invoice.generatePaymentLink': 'Generar enlace de pago (Revolut)',
    'invoice.markSent': 'Marcar como enviada',
    'invoice.markPaid': 'Marcar como cobrada → añade a Caja',
    'invoice.cancelInvoice': 'Anular',
    'invoice.downloadPdf': 'Descargar PDF',
    'invoice.verifactu.testMode': 'modo pruebas · no activado',
    'invoice.verifactu.help': 'Genera el registro encadenado (huella SHA-256) y el QR de cotejo de la AEAT. No es cumplimiento activo hasta el alta en la AEAT y la declaración responsable.',
    'invoice.verifactu.generating': 'Generando…',
    'invoice.verifactu.generate': 'Generar registro Verifactu',
    'invoice.verifactu.qrAlt': 'QR Verifactu',
    'invoice.verifactu.hash': 'Huella',
    'invoice.verifactu.previous': 'Encadenada a',
    'invoice.verifactu.first': '(primer registro)',
    'invoice.status.draft': 'Borrador',
    'invoice.status.sent': 'Enviada',
    'invoice.status.paid': 'Cobrada',
    'invoice.status.overdue': 'Vencida',
    'invoice.status.cancelled': 'Anulada',
    'timelog.locationUnavailable': 'Ubicación no disponible — se fichará sin GPS',
    'timelog.worker': 'Trabajador',
    'timelog.clockIn': 'Entrada',
    'timelog.clockOut': 'Salida',
    'timelog.hours': 'Horas',
    'timelog.entryLocation': 'Ubicación entrada',
    'timelog.sheetName': 'Control horario',
    'timelog.activeSince': 'Jornada activa desde {time}',
    'timelog.noActiveShift': 'Sin jornada activa',
    'timelog.clockingIn': 'Fichando entrada...',
    'timelog.clockInAction': 'Fichar entrada',
    'timelog.clockingOut': 'Fichando salida...',
    'timelog.clockOutAction': 'Fichar salida',
    'timelog.shiftCount': '{count} jornadas',
    'timelog.duration': 'Duración',
    'timelog.location': 'Ubicación',
    'timelog.empty': 'Aún no hay registros',
    'timelog.active': 'Activa',
    'ops.nav.section': 'OPS — Finanzas', 'ops.nav.dashboard': 'Dashboard OPS',
    'ops.nav.invoices': 'Facturas', 'ops.nav.cash': 'Caja',
    'ops.nav.timelog': 'Control Horario', 'ops.nav.clients': 'Clientes OPS',
    'ops.nav.visits': 'Visitas', 'ops.nav.venues': 'Locales', 'ops.nav.ai': 'Asistente IA OPS', 'ops.nav.books': 'Libros', 'ops.nav.bank': 'Banco', 'ops.nav.tax': 'Fiscalidad',
    'tax.title': 'Fiscalidad y legislación aplicable',
    'tax.subtitle': 'Referencia interna para Novitum/PulseCosta: solo obligaciones que pueden afectarnos por operativa interna o prestación de servicios B2B/B2C. Validar siempre con el gestor antes de presentar modelos.',
    'tax.defaultCountry': 'Base fiscal',
    'tax.operatingScope': 'Alcance',
    'tax.scopeText': 'OÜ estonia, servicios software/IA, clientes B2B/B2C internacionales',
    'tax.warningTitle': 'No usar por defecto',
    'tax.warningText': 'IVA español, Finlandia o UK solo si el gestor confirma registro, establecimiento o consumidor local.',
    'tax.internal': 'Operativa interna',
    'tax.services': 'Servicios B2B/B2C',
    'tax.form': 'Modelo / declaración',
    'tax.applies': 'Aplicación',
    'tax.cadence': 'Periodicidad',
    'tax.scope': 'Ámbito',
    'tax.note': 'Nota para gestoría',
    'tax.applies.yes': 'Aplica',
    'tax.applies.conditional': 'Si procede',
    'tax.applies.watch': 'Vigilar',
    'venues.title': 'Locales (Costa del Sol)',
    'venues.subtitle': 'locales en el sistema — prospects para comercial',
    'venues.searchPh': 'Buscar por nombre o dirección…',
    'venues.allCategories': 'Todas las categorías',
    'venues.unclaimed': 'Sin reclamar',
    'venues.unvisited': 'Sin visitar',
    'venues.category': 'Categoría',
    'venues.premium': 'Premium',
    'venues.claimed': 'Reclamado',
    'venues.cold': 'Frío',
    'venues.prev': 'Anterior',
    'venues.next': 'Siguiente',
    'venues.page': 'Página',
    'venues.of': 'de',
    'venues.empty': 'Sin resultados',
    'campaign.audience': 'Audiencia',
    'campaign.copyCsv': 'Copiar CSV',
    'campaign.channel': 'Canal',
    'campaign.leads': 'Leads',
    'campaign.accounts': 'Cuentas',
    'campaign.venues': 'Locales',
    'campaign.manual': 'Manual',
    'campaign.loadingContacts': 'cargando contactos',
    'campaign.selectedWithChannel': '{count} seleccionados · {channel}',
    'campaign.allZones': 'Todas las zonas',
    'campaign.allCategories': 'Todas las categorías',
    'campaign.addManual': 'Añadir contacto manual',
    'campaign.addManualHelp': 'Para un local que falte o una prueba puntual.',
    'campaign.namePh': 'Nombre del local',
    'campaign.add': 'Añadir',
    'campaign.message': 'Mensaje',
    'campaign.copy': 'Copiar',
    'campaign.subject': 'Asunto',
    'campaign.text': 'Texto',
    'campaign.preview': 'Vista previa',
    'campaign.recipients': 'Destinatarios',
    'campaign.showing': 'Mostrando {shown} de {total}',
    'campaign.unselectShown': 'Quitar mostrados',
    'campaign.selectShown': 'Seleccionar mostrados',
    'campaign.clearAll': 'Limpiar todo',
    'campaign.selectFiltered': 'Seleccionar filtrados',
    'campaign.searchPh': 'Buscar por nombre, zona o contacto',
    'campaign.assisted': 'Envío asistido',
    'campaign.assistedHelp': 'Selecciona contactos y trabaja uno a uno.',
    'campaign.reviewed': '{done} de {total} revisados',
    'campaign.start': 'Iniciar',
    'campaign.reviewedTitle': 'Campaña revisada',
    'campaign.sentSkipped': '{sent} enviados · {skipped} saltados',
    'campaign.open': 'Abrir',
    'campaign.markSent': 'Marcar enviado',
    'campaign.skip': 'Saltar',
    'campaign.restart': 'Reiniciar',
    'campaign.emailBatches': 'Lotes de email',
    'campaign.emailBatchesHelp': 'Envía seleccionados en BCC por tandas de 50 o 60.',
    'campaign.batchSize': 'Tamaño',
    'campaign.batchSummary': 'Lote {current} de {total} · {count} emails',
    'campaign.noEmailBatch': 'Selecciona destinatarios con email para crear lotes.',
    'campaign.copyBatchEmails': 'Copiar emails',
    'campaign.openBatch': 'Abrir lote',
    'campaign.sendBrevo': 'Enviar por Brevo',
    'campaign.prevBatch': 'Anterior',
    'campaign.nextBatch': 'Siguiente',
    'campaign.confirmBrevo': 'Vas a enviar este lote a {count} emails por Brevo. ¿Continuar?',
    'campaign.batchPersonalizationWarning': 'En lotes, {nombre} se sustituye por un saludo genérico.',
    'campaign.loadingEmpty': 'Cargando contactos...',
    'campaign.noContacts': 'No hay contactos disponibles para este canal.',
    'campaign.more': 'Mostrar {count} más de {total}',
    'campaign.openEmail': 'Abrir email',
    'campaign.openWhatsapp': 'Abrir WhatsApp',
    'campaign.statusLoadError': 'No se pudieron cargar los contactos',
    'campaign.statusCsvCopied': '{count} contactos copiados como CSV',
    'campaign.statusSelectFirst': 'Selecciona destinatarios antes de iniciar la campaña',
    'campaign.statusPrepared': 'Campaña preparada con {count} destinatarios',
    'campaign.statusReviewed': 'Campaña revisada: {sent} enviados, {skipped} saltados',
    'campaign.statusManualMissing': 'Añade nombre y al menos email o teléfono',
    'campaign.statusManualAdded': '{name} añadido manualmente',
    'campaign.statusMessageCopied': 'Mensaje copiado',
    'campaign.statusBatchEmailsCopied': 'Emails del lote copiados',
    'campaign.statusBrevoSent': 'Lote enviado por Brevo a {count} destinatarios',
    'campaign.sourceAccount': 'Cuenta · {value}',
    'campaign.sourceVenue': 'Local · {value}',
    'campaign.sourceVenueNoCategory': 'Sin categoría',
    'campaign.sourceLead': 'Lead · {value}',
    'campaign.sourceManual': 'Manual',
    'category.bar': 'Bar',
    'category.hotel': 'Hotel',
    'category.restaurant': 'Restaurante',
    'category.nightclub': 'Discoteca',
    'category.beach_club': 'Beach club',
    'category.wellness': 'Bienestar',
    'category.other': 'Otro',
    'campaign.template.email.subject': 'PulseCosta: activamos visibilidad local en la Costa del Sol',
    'campaign.template.email.body': 'Hola {nombre},\n\nSoy Cipriano de PulseCosta. Estamos preparando la campaña local para dar más visibilidad a negocios de la Costa del Sol con horarios, fotos y contacto actualizado.\n\n¿Te viene bien que revisemos vuestra ficha y la dejemos lista esta semana?\n\nGracias,\nPulseCosta',
    'campaign.template.whatsapp.subject': '',
    'campaign.template.whatsapp.body': 'Hola {nombre}, soy Cipriano de PulseCosta. Estamos actualizando fichas de negocios de la Costa del Sol para mejorar visibilidad, horarios y fotos. ¿Te viene bien que revisemos la vuestra esta semana?',
  },
  en: {
    'sec.main': 'Main', 'sec.prospecting': 'Prospecting',
    'sec.ops': 'Operations', 'sec.analytics': 'Analytics',
    'nav.dashboard': 'Dashboard', 'nav.pipeline': 'Pipeline',
    'nav.leads': 'Leads', 'nav.accounts': 'Accounts',
    'nav.tasks': 'Tasks', 'nav.activities': 'Activity', 'nav.reports': 'Reports',
    'nav.campaigns': 'Campaigns',
    'btn.newLead': '+ New Lead', 'btn.newAccount': '+ New Account',
    'btn.export': 'Export CSV', 'btn.signin': 'Sign In',
    'btn.save': 'Save', 'btn.cancel': 'Cancel',
    'btn.edit': 'Edit', 'common.yes': 'Yes', 'common.no': 'No',
    'filter.allZones': 'All zones', 'filter.allPlans': 'All plans',
    'filter.allSources': 'All sources', 'filter.allStatuses': 'All statuses',
    'filter.allAgents': 'All agents',
    'label.zone': 'Zone', 'label.plan': 'Plan', 'label.stage': 'Stage',
    'label.agent': 'Agent', 'label.date': 'Date', 'label.status': 'Status',
    'label.priority': 'Priority', 'label.name': 'Name', 'label.type': 'Type',
    'label.source': 'Source', 'label.mrr': 'MRR', 'label.contact': 'Contact',
    'label.notes': 'Notes', 'label.address': 'Address',
    'common.back': 'Back',
    'dash.activeLeads': 'Active Leads', 'dash.activeAccounts': 'Active Accounts',
    'dash.mrr': 'Estimated MRR', 'dash.overdue': 'Overdue Tasks',
    'dash.recentActivity': 'Recent Activity', 'dash.priorityTasks': 'Priority Tasks',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'See all →', 'common.today': 'Today',
    'common.thisWeek': 'This week', 'common.thisMonth': 'This month',
    'common.search': 'Search...', 'common.loading': 'Loading...',
    'common.email': 'Email', 'common.phone': 'Phone',
    'common.password': 'Password', 'common.saving': 'Saving...',
    'common.saveError': 'Could not save',
    'common.brandBadge': 'Commercial CRM', 'common.close': 'Close',
    'common.menuOpen': 'Open menu', 'common.menuClose': 'Close menu',
    'nav.assistant': 'AI Assistant',
    'auth.signOut': 'Sign out', 'role.superAdmin': 'Super Admin',
    'app.installTitle': 'Install app',
    'app.installInstructions': 'Install PulseCosta CRM\n\niOS Safari → Share → Add to Home Screen\nAndroid/Chrome → Menu ⋮ → Install app\nChrome desktop → Menu ⋮ → Install app',
    'login.subtitle': 'CRM · Commercial Panel',
    'login.passwordRequired': 'Enter your password',
    'login.invalidCredentials': 'Incorrect credentials',
    'login.showPassword': 'Show password',
    'login.hidePassword': 'Hide password',
    'login.footer': 'Fuengirola · Marbella · Estepona · Costa del Sol',
    'placeholder.initialNotes': 'Initial notes...',
    'placeholder.contactName': 'Contact name',
    'placeholder.taskTitle': 'Call Hotel Bahia',
    'placeholder.activityDescription': 'Describe the activity...',
    'type.local': 'Venue / Bar / Rest.',
    'type.hotel': 'Hotel',
    'lead.convertConfirm': 'Convert "{name}" into a pipeline account?',
    'lead.convertError': 'Could not convert',
    'lead.converting': 'Converting...',
    'lead.convertToAccount': 'Convert to account',
    'lead.call': 'Call',
    'lead.originNote': 'Origin: lead #{id}{source}',
    'assistant.summary': 'Daily Summary',
    'assistant.visits': 'Visit Analysis',
    'assistant.ask': 'Ask',
    'assistant.subtitle': 'Local AI (Spark) · PulseCosta CRM',
    'assistant.generate': 'Generate',
    'assistant.empty': 'Select a mode and generate your first analysis.',
    'assistant.loading': 'Analysing with local AI (Spark)...',
    'assistant.questionPh': 'Ask something about the CRM...',
    'assistant.send': 'Send',
    'assistant.clear': 'Clear conversation',
    'account.notFound': 'Account not found.',
    'account.overview': 'Overview',
    'account.contractDetails': 'Contract details',
    'account.perMonth': 'month',
    'account.perYear': 'year',
    'account.annualMrr': 'Annual MRR',
    'account.createdAt': 'Created',
    'account.updatedAt': 'Last update',
    'account.noActivity': 'No activity recorded.',
    'account.tasksHelp': 'Tasks linked to this account are managed from the Tasks section.',
    'label.companyName': 'Company / Name',
    'label.contactPerson': 'Contact person',
    'label.postalCode': 'Postal code',
    'label.city': 'City',
    'label.country': 'Country',
    'ops.clients.title': 'Clients',
    'ops.clients.new': 'New client',
    'ops.clients.edit': 'Edit client',
    'ops.clients.save': 'Save client',
    'ops.clients.searchPh': 'Search by name, city, or tax/VAT ID...',
    'ops.clients.empty': 'No clients found',
    'ops.clients.pending': 'Outstanding',
    'ops.clients.invoiceHistory': 'Invoice history',
    'ops.clients.visitHistory': 'Visit history',
    'ops.clients.noVisits': 'No visits',
    'ops.clients.addressPh': 'Street and number',
    'visit.status.pending': 'Pending',
    'visit.status.follow_up': 'Follow-up',
    'visit.status.closed': 'Closed',
    'visit.status.lost': 'Lost',
    'ops.visits.title': 'Visit CRM',
    'ops.visits.new': 'New visit',
    'ops.visits.edit': 'Edit visit',
    'ops.visits.save': 'Save visit',
    'ops.visits.empty': 'No visits found',
    'ops.visits.all': 'All',
    'ops.visits.prospectSection': 'Prospect / Company',
    'ops.visits.publicSearch': 'Search venue in the public database (Costa del Sol)',
    'ops.visits.publicSearchPh': 'Type 2+ letters from the name...',
    'ops.visits.publicSearchHelp': 'Not in the database? Leave this field empty and fill it in manually below as a free prospect.',
    'ops.visits.publicVenue': 'Public database venue:',
    'ops.visits.changeVenue': 'Change',
    'ops.visits.venueCompany': 'Venue / Company',
    'ops.visits.detailsSection': 'Visit details',
    'ops.visits.existingClient': 'Existing client (optional — only for upsell visits)',
    'ops.visits.newProspect': '— Prospect (new) —',
    'ops.visits.clientSearchPh': 'Search client...',
    'ops.visits.selectPlan': 'Select plan...',
    'ops.visits.proposalSent': 'Proposal sent',
    'ops.visits.followUpDate': 'Follow-up date',
    'ops.visits.nextAction': 'Next action',
    'ops.visits.visitDate': 'Visit',
    'ops.visits.followUp': 'Follow-up',
    'ops.visits.client': 'Client',
    'ops.visits.fieldTitle': 'Registered in PulseField',
    'ops.visits.convertToClient': 'Convert to client',
    'ops.visits.converting': 'Converting...',
    'ops.visits.convertError': 'Could not convert to client',
    'ops.visits.clientCreated': 'Client "{name}" created. Go to Invoices to create the first invoice.',
    'ops.cash.title': 'Cash',
    'ops.cash.income': 'Income',
    'ops.cash.expense': 'Expense',
    'ops.cash.newIncome': 'New income',
    'ops.cash.newExpense': 'New expense',
    'ops.cash.addIncome': 'Add income',
    'ops.cash.addExpense': 'Add expense',
    'ops.cash.concept': 'Concept',
    'ops.cash.conceptIncomePh': 'e.g. Monthly subscription La Bahia',
    'ops.cash.conceptExpensePh': 'e.g. Hostinger VPS hosting',
    'ops.cash.amount': 'Amount',
    'ops.cash.category': 'Category',
    'ops.cash.select': 'Select...',
    'ops.cash.vatType': 'VAT type',
    'ops.cash.vatNormal': 'Normal (with VAT)',
    'ops.cash.vatReverse': 'Reverse charge (EU B2B)',
    'ops.cash.vatExempt': 'Exempt',
    'ops.cash.vatRate': 'VAT rate (%)',
    'ops.cash.linkInvoice': 'Link to invoice (optional)',
    'ops.cash.linkClient': 'Client (optional)',
    'ops.cash.noInvoice': 'None',
    'ops.cash.noClient': 'None',
    'ops.cash.invoiceSearchPh': 'Search invoice...',
    'ops.cash.clientSearchPh': 'Search client...',
    'ops.cash.recurring': 'Recurring',
    'ops.cash.monthly': 'Monthly',
    'ops.cash.quarterly': 'Quarterly',
    'ops.cash.totalIncome': 'Total income',
    'ops.cash.totalExpenses': 'Total expenses',
    'ops.cash.noMovements': 'No movements yet',
    'ops.cash.category.Invoice': 'Invoice',
    'ops.cash.category.Subscription': 'Subscription',
    'ops.cash.category.Grant': 'Grant',
    'ops.cash.category.Server': 'Server',
    'ops.cash.category.Salary': 'Salaries',
    'ops.cash.category.Travel': 'Travel',
    'ops.cash.category.Marketing': 'Marketing',
    'ops.cash.category.Legal': 'Legal',
    'ops.cash.category.Software': 'Software',
    'ops.cash.category.Office': 'Office',
    'ops.cash.category.Other': 'Other',
    'stage.new': 'New', 'stage.attempting_contact': 'Attempting contact',
    'stage.contacted': 'Contacted', 'stage.interested': 'Interested',
    'stage.demo_scheduled': 'Demo scheduled', 'stage.proposal_sent': 'Proposal sent',
    'stage.negotiation': 'Negotiation', 'stage.onboarding_pending': 'Onboarding',
    'stage.payment_pending': 'Payment pending', 'stage.active': 'Active', 'stage.converted': 'Converted',
    'stage.at_risk': 'At risk', 'stage.churned': 'Churned', 'stage.lost': 'Lost',
    'plan.premium_local': 'Premium Local', 'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotel Analytics', 'plan.hotel_elite': 'Hotel Elite',
    'priority.urgent': 'Urgent', 'priority.high': 'High',
    'priority.medium': 'Medium', 'priority.low': 'Low',
    'activity.call': 'Call', 'activity.email': 'Email',
    'activity.visit': 'Visit', 'activity.note': 'Note', 'activity.system': 'System',
    'reports.title': 'Reports', 'reports.download': 'Download',
    'reports.type': 'Report type', 'reports.period': 'Period',
    'reports.today': 'Today', 'reports.week': 'This week',
    'reports.month': 'This month', 'reports.quarter': 'Quarter',
    'reports.year': 'This year', 'reports.custom': '📅 Custom',
    'reports.pdf': '⬇ PDF', 'reports.excel': '⬇ Excel',
    'report.executive': '📋 Executive summary', 'report.pipeline': '⬡ Pipeline & conversion',
    'report.activity': '↺ Commercial activity', 'report.leads': '◎ Leads & prospecting',
    'report.billing': '€ Billing & MRR', 'report.agents': '👤 Agent performance',
    'lead.new': 'New Lead', 'lead.name': 'Venue / hotel name',
    'lead.phone': 'Contact phone',
    'ops.loading': 'Loading...', 'ops.title': 'OPS Dashboard',
    'ops.allTime': 'All time', 'ops.thisMonth': 'This month',
    'ops.lastMonth': 'Last month', 'ops.thisYear': 'This year',
    'ops.resetData': 'Reset data', 'ops.collected': 'Collected',
    'ops.outstanding': 'Outstanding', 'ops.cashBalance': 'Cash balance',
    'ops.forecast': '30-day forecast', 'ops.overdueInvoices': 'Overdue invoices',
    'ops.daysOverdue': 'd overdue', 'ops.vatReport': 'VAT report',
    'ops.outputVat': 'Output VAT', 'ops.inputVat': 'Input VAT',
    'ops.netVat': 'Net VAT payable', 'ops.recentCash': 'Recent movements',
    'ops.noMovements': 'No movements', 'ops.latestInvoices': 'Latest invoices',
    'ops.noInvoices': 'No invoices', 'ops.invoiceNumber': 'Number',
    'ops.invoiceDue': 'Due date', 'ops.clientName': 'Client',
    'ops.date': 'Date', 'ops.total': 'Total', 'ops.status': 'Status',
    'invoice.new': 'New invoice',
    'invoice.create': 'Create invoice',
    'invoice.number': 'Invoice number',
    'invoice.selectClient': 'Select client…',
    'invoice.searchClient': 'Search client…',
    'invoice.issueDate': 'Issue date',
    'invoice.dueDate': 'Due date',
    'invoice.dueShort': 'Due',
    'invoice.paymentMethod': 'Payment method',
    'invoice.payment.bankTransfer': 'Bank transfer',
    'invoice.payment.cash': 'Cash',
    'invoice.type.normal': 'Normal',
    'invoice.type.recurring': 'Recurring',
    'invoice.interval': 'Interval',
    'invoice.interval.monthly': 'Monthly',
    'invoice.interval.quarterly': 'Quarterly',
    'invoice.vatJurisdiction': 'VAT jurisdiction',
    'invoice.vatRateFor': 'VAT rate · {jurisdiction} (%)',
    'invoice.jurisdiction.estonia': 'Estonia',
    'invoice.jurisdiction.spain': 'Spain',
    'invoice.jurisdiction.eu': 'EU',
    'invoice.jurisdiction.exento': 'Exempt',
    'invoice.reverseTitle': 'Reverse charge (Art. 44)',
    'invoice.reverseHelp': 'VAT = 0%. The client VAT number is required. The legal note will appear in the PDF.',
    'invoice.missingVatWarning': 'This client has no VAT number. Add it in Clients before issuing the invoice.',
    'invoice.lines': 'Lines',
    'invoice.description': 'Description',
    'invoice.qty': 'Qty',
    'invoice.unitPrice': 'Unit price',
    'invoice.amount': 'Amount',
    'invoice.serviceDescription': 'Service description',
    'invoice.addLine': '+ Add line',
    'invoice.taxableBase': 'Taxable base',
    'invoice.vatType': 'VAT type',
    'invoice.vat.normal': 'VAT',
    'invoice.vat.normalRate': 'VAT {rate}%',
    'invoice.vat.reverseShort': 'Reverse charge',
    'invoice.vat.exempt': 'Exempt',
    'invoice.notesPh': 'Internal notes or additional information',
    'invoice.error.selectClient': 'Select a client',
    'invoice.detailTitle': 'Invoice {number}',
    'invoice.issueDue': 'Issue / Due date',
    'invoice.noDueDate': 'No due date',
    'invoice.paymentLink': 'Payment link',
    'invoice.generatePaymentLink': 'Generate payment link (Revolut)',
    'invoice.markSent': 'Mark as sent',
    'invoice.markPaid': 'Mark as paid → add to Cash',
    'invoice.cancelInvoice': 'Cancel',
    'invoice.downloadPdf': 'Download PDF',
    'invoice.verifactu.testMode': 'test mode · not active',
    'invoice.verifactu.help': 'Generate the chained record (SHA-256 fingerprint) and the AEAT verification QR. This is not active compliance until AEAT registration and the responsible declaration are completed.',
    'invoice.verifactu.generating': 'Generating…',
    'invoice.verifactu.generate': 'Generate Verifactu record',
    'invoice.verifactu.qrAlt': 'Verifactu QR',
    'invoice.verifactu.hash': 'Fingerprint',
    'invoice.verifactu.previous': 'Chained to',
    'invoice.verifactu.first': '(first record)',
    'invoice.status.draft': 'Draft',
    'invoice.status.sent': 'Sent',
    'invoice.status.paid': 'Paid',
    'invoice.status.overdue': 'Overdue',
    'invoice.status.cancelled': 'Cancelled',
    'timelog.locationUnavailable': 'Location unavailable — clock-in will be saved without GPS',
    'timelog.worker': 'Worker',
    'timelog.clockIn': 'Clock in',
    'timelog.clockOut': 'Clock out',
    'timelog.hours': 'Hours',
    'timelog.entryLocation': 'Clock-in location',
    'timelog.sheetName': 'Time log',
    'timelog.activeSince': 'Active shift since {time}',
    'timelog.noActiveShift': 'No active shift',
    'timelog.clockingIn': 'Clocking in...',
    'timelog.clockInAction': 'Clock in',
    'timelog.clockingOut': 'Clocking out...',
    'timelog.clockOutAction': 'Clock out',
    'timelog.shiftCount': '{count} shifts',
    'timelog.duration': 'Duration',
    'timelog.location': 'Location',
    'timelog.empty': 'No records yet',
    'timelog.active': 'Active',
    'ops.nav.section': 'OPS — Finance', 'ops.nav.dashboard': 'OPS Dashboard',
    'ops.nav.invoices': 'Invoices', 'ops.nav.cash': 'Cash',
    'ops.nav.timelog': 'Time Log', 'ops.nav.clients': 'OPS Clients',
    'ops.nav.visits': 'Visits', 'ops.nav.venues': 'Venues', 'ops.nav.ai': 'AI Assistant OPS', 'ops.nav.books': 'Books', 'ops.nav.bank': 'Bank', 'ops.nav.tax': 'Tax',
    'tax.title': 'Tax and applicable legislation',
    'tax.subtitle': 'Internal reference for Novitum/PulseCosta: only obligations that may affect us through internal operations or B2B/B2C service delivery. Always validate with the accountant before filing.',
    'tax.defaultCountry': 'Tax base',
    'tax.operatingScope': 'Scope',
    'tax.scopeText': 'Estonian OÜ, software/AI services, international B2B/B2C clients',
    'tax.warningTitle': 'Do not use by default',
    'tax.warningText': 'Spanish VAT, Finland or UK only if the accountant confirms registration, establishment, or local consumer obligations.',
    'tax.internal': 'Internal operations',
    'tax.services': 'B2B/B2C services',
    'tax.form': 'Form / return',
    'tax.applies': 'Application',
    'tax.cadence': 'Cadence',
    'tax.scope': 'Scope',
    'tax.note': 'Accounting note',
    'tax.applies.yes': 'Applies',
    'tax.applies.conditional': 'If relevant',
    'tax.applies.watch': 'Watch',
    'venues.title': 'Venues (Costa del Sol)',
    'venues.subtitle': 'venues in the system — commercial prospects',
    'venues.searchPh': 'Search by name or address…',
    'venues.allCategories': 'All categories',
    'venues.unclaimed': 'Unclaimed',
    'venues.unvisited': 'Not yet visited',
    'venues.category': 'Category',
    'venues.premium': 'Premium',
    'venues.claimed': 'Claimed',
    'venues.cold': 'Cold',
    'venues.prev': 'Previous',
    'venues.next': 'Next',
    'venues.page': 'Page',
    'venues.of': 'of',
    'venues.empty': 'No results',
    'campaign.audience': 'Audience',
    'campaign.copyCsv': 'Copy CSV',
    'campaign.channel': 'Channel',
    'campaign.leads': 'Leads',
    'campaign.accounts': 'Accounts',
    'campaign.venues': 'Venues',
    'campaign.manual': 'Manual',
    'campaign.loadingContacts': 'loading contacts',
    'campaign.selectedWithChannel': '{count} selected · {channel}',
    'campaign.allZones': 'All zones',
    'campaign.allCategories': 'All categories',
    'campaign.addManual': 'Add manual contact',
    'campaign.addManualHelp': 'For a missing venue or a quick test.',
    'campaign.namePh': 'Venue name',
    'campaign.add': 'Add',
    'campaign.message': 'Message',
    'campaign.copy': 'Copy',
    'campaign.subject': 'Subject',
    'campaign.text': 'Text',
    'campaign.preview': 'Preview',
    'campaign.recipients': 'Recipients',
    'campaign.showing': 'Showing {shown} of {total}',
    'campaign.unselectShown': 'Unselect shown',
    'campaign.selectShown': 'Select shown',
    'campaign.clearAll': 'Clear all',
    'campaign.selectFiltered': 'Select filtered',
    'campaign.searchPh': 'Search by name, zone, or contact',
    'campaign.assisted': 'Assisted sending',
    'campaign.assistedHelp': 'Select contacts and work through them one by one.',
    'campaign.reviewed': '{done} of {total} reviewed',
    'campaign.start': 'Start',
    'campaign.reviewedTitle': 'Campaign reviewed',
    'campaign.sentSkipped': '{sent} sent · {skipped} skipped',
    'campaign.open': 'Open',
    'campaign.markSent': 'Mark sent',
    'campaign.skip': 'Skip',
    'campaign.restart': 'Restart',
    'campaign.emailBatches': 'Email batches',
    'campaign.emailBatchesHelp': 'Send selected recipients in BCC batches of 50 or 60.',
    'campaign.batchSize': 'Size',
    'campaign.batchSummary': 'Batch {current} of {total} · {count} emails',
    'campaign.noEmailBatch': 'Select recipients with email to create batches.',
    'campaign.copyBatchEmails': 'Copy emails',
    'campaign.openBatch': 'Open batch',
    'campaign.sendBrevo': 'Send with Brevo',
    'campaign.prevBatch': 'Previous',
    'campaign.nextBatch': 'Next',
    'campaign.confirmBrevo': 'This will send the current batch to {count} emails through Brevo. Continue?',
    'campaign.batchPersonalizationWarning': 'In batches, {nombre} is replaced by a generic greeting.',
    'campaign.loadingEmpty': 'Loading contacts...',
    'campaign.noContacts': 'No contacts available for this channel.',
    'campaign.more': 'Show {count} more of {total}',
    'campaign.openEmail': 'Open email',
    'campaign.openWhatsapp': 'Open WhatsApp',
    'campaign.statusLoadError': 'Contacts could not be loaded',
    'campaign.statusCsvCopied': '{count} contacts copied as CSV',
    'campaign.statusSelectFirst': 'Select recipients before starting the campaign',
    'campaign.statusPrepared': 'Campaign prepared with {count} recipients',
    'campaign.statusReviewed': 'Campaign reviewed: {sent} sent, {skipped} skipped',
    'campaign.statusManualMissing': 'Add a name and at least an email or phone number',
    'campaign.statusManualAdded': '{name} added manually',
    'campaign.statusMessageCopied': 'Message copied',
    'campaign.statusBatchEmailsCopied': 'Batch emails copied',
    'campaign.statusBrevoSent': 'Batch sent through Brevo to {count} recipients',
    'campaign.sourceAccount': 'Account · {value}',
    'campaign.sourceVenue': 'Venue · {value}',
    'campaign.sourceVenueNoCategory': 'No category',
    'campaign.sourceLead': 'Lead · {value}',
    'campaign.sourceManual': 'Manual',
    'category.bar': 'Bar',
    'category.hotel': 'Hotel',
    'category.restaurant': 'Restaurant',
    'category.nightclub': 'Nightclub',
    'category.beach_club': 'Beach club',
    'category.wellness': 'Wellness',
    'category.other': 'Other',
    'campaign.template.email.subject': 'PulseCosta: activate local visibility on the Costa del Sol',
    'campaign.template.email.body': 'Hello {nombre},\n\nI am Cipriano from PulseCosta. We are preparing the local campaign to give Costa del Sol businesses more visibility with updated hours, photos, and contact details.\n\nWould it suit you if we reviewed your listing and got it ready this week?\n\nThank you,\nPulseCosta',
    'campaign.template.whatsapp.subject': '',
    'campaign.template.whatsapp.body': 'Hello {nombre}, I am Cipriano from PulseCosta. We are updating business listings on the Costa del Sol to improve visibility, opening hours, and photos. Would it suit you if we reviewed yours this week?',
  },
  fi: {
    'sec.main': 'Etusivu',
    'sec.prospecting': 'Etsintä',
    'sec.ops': 'Operatiivinen',
    'sec.analytics': 'Analyysi',
    'nav.dashboard': 'Kojelauta',
    'nav.pipeline': 'Myyntiputki',
    'nav.leads': 'Liidit',
    'nav.accounts': 'Asiakkuudet',
    'nav.tasks': 'Tehtävät',
    'nav.activities': 'Toiminta',
    'nav.reports': 'Raportit',
    'nav.campaigns': 'Kampanjat',
    'btn.newLead': '+ Uusi liidi',
    'btn.newAccount': '+ Uusi tili',
    'btn.export': 'Vie CSV-tiedosto',
    'btn.signin': 'Kirjaudu sisään',
    'btn.save': 'Tallenna',
    'btn.cancel': 'Peruuta',
    'btn.edit': 'Muokkaa',
    'common.yes': 'Kyllä',
    'common.no': 'Ei',
    'filter.allZones': 'Kaikki alueet',
    'filter.allPlans': 'Kaikki paketit',
    'filter.allSources': 'Kaikki lähteet',
    'filter.allStatuses': 'Kaikki tilat',
    'filter.allAgents': 'Kaikki myyjät',
    'label.zone': 'Alue',
    'label.plan': 'Paketti',
    'label.stage': 'Vaihe',
    'label.agent': 'Myyjä',
    'label.date': 'Päivämäärä',
    'label.status': 'Tila',
    'label.priority': 'Prioriteetti',
    'label.name': 'Nimi',
    'label.type': 'Tyyppi',
    'label.source': 'Lähde',
    'label.mrr': 'MRR',
    'label.contact': 'Yhteystiedot',
    'label.notes': 'Huomautukset',
    'label.address': 'Osoite',
    'common.back': 'Takaisin',
    'dash.activeLeads': 'Aktiiviset liidit',
    'dash.activeAccounts': 'Aktiiviset tilit',
    'dash.mrr': 'Arvioitu MRR',
    'dash.overdue': 'Erääntyneet tehtävät',
    'dash.recentActivity': 'Viimeaikaiset toimet',
    'dash.priorityTasks': 'Ensisijaiset tehtävät',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'Näytä kaikki →',
    'common.today': 'Tänään',
    'common.thisWeek': 'Tällä viikolla',
    'common.thisMonth': 'Tässä kuussa',
    'common.search': 'Hae...',
    'common.loading': 'Ladataan...',
    'common.email': 'Sähköposti',
    'common.phone': 'Puhelin',
    'common.password': 'Salasana',
    'common.saving': 'Tallennetaan...',
    'common.saveError': 'Tallennus epäonnistui',
    'common.brandBadge': 'Myynnin CRM',
    'common.close': 'Sulje',
    'common.menuOpen': 'Avaa valikko',
    'common.menuClose': 'Sulje valikko',
    'nav.assistant': 'Tekoälyavustaja',
    'auth.signOut': 'Kirjaudu ulos',
    'role.superAdmin': 'Pääkäyttäjä',
    'app.installTitle': 'Asenna sovellus',
    'app.installInstructions': 'Asenna PulseCosta CRM\n\niOS Safari → Jaa → Lisää Koti-valikkoon\nAndroid/Chrome → Valikko ⋮ → Asenna sovellus\nChrome desktop → Valikko ⋮ → Asenna sovellus',
    'login.subtitle': 'CRM · Myynnin paneeli',
    'login.passwordRequired': 'Syötä salasana',
    'login.invalidCredentials': 'Virheelliset tunnistetiedot',
    'login.showPassword': 'Näytä salasana',
    'login.hidePassword': 'Piilota salasana',
    'login.footer': 'Fuengirola · Marbella · Estepona · Costa del Sol',
    'placeholder.initialNotes': 'Alkumuistiinpanot...',
    'placeholder.contactName': 'Yhteyshenkilön nimi',
    'placeholder.taskTitle': 'Soita Hotel Bahiaan',
    'placeholder.activityDescription': 'Kuvaile toimintaa...',
    'type.local': 'Toimipiste / Baari / Ravintola',
    'type.hotel': 'Hotelli',
    'lead.convertConfirm': 'Muuntaako "{name}" myyntiputken asiakkuudeksi?',
    'lead.convertError': 'Muunto epäonnistui',
    'lead.converting': 'Muunnetaan...',
    'lead.convertToAccount': 'Muunna asiakkuudeksi',
    'lead.call': 'Soita',
    'lead.originNote': 'Alkuperä: liidi #{id}{source}',
    'assistant.summary': 'Päivän yhteenveto',
    'assistant.visits': 'Vierailuanalyysi',
    'assistant.ask': 'Kysy',
    'assistant.subtitle': 'Paikallinen tekoäly (Spark) · PulseCosta CRM',
    'assistant.generate': 'Luo',
    'assistant.empty': 'Valitse tila ja luo ensimmäinen analyysi.',
    'assistant.loading': 'Analysoidaan paikallisella tekoälyllä (Spark)...',
    'assistant.questionPh': 'Kysy jotain CRM:stä...',
    'assistant.send': 'Lähetä',
    'assistant.clear': 'Tyhjennä keskustelu',
    'account.notFound': 'Asiakkuutta ei löydy.',
    'account.overview': 'Yhteenveto',
    'account.contractDetails': 'Sopimuksen tiedot',
    'account.perMonth': 'kuukausi',
    'account.perYear': 'vuosi',
    'account.annualMrr': 'Vuosittainen MRR',
    'account.createdAt': 'Luotu',
    'account.updatedAt': 'Viimeisin päivitys',
    'account.noActivity': 'Toimintaa ei ole kirjattu.',
    'account.tasksHelp': 'Tähän asiakkuuteen liittyviä tehtäviä hallitaan Tehtävät-osiossa.',
    'label.companyName': 'Yritys / nimi',
    'label.contactPerson': 'Yhteyshenkilö',
    'label.postalCode': 'Postinumero',
    'label.city': 'Kaupunki',
    'label.country': 'Maa',
    'ops.clients.title': 'Asiakkaat',
    'ops.clients.new': 'Uusi asiakas',
    'ops.clients.edit': 'Muokkaa asiakasta',
    'ops.clients.save': 'Tallenna asiakas',
    'ops.clients.searchPh': 'Hae nimellä, kaupungilla tai vero-/VAT-tunnuksella...',
    'ops.clients.empty': 'Asiakkaita ei löytynyt',
    'ops.clients.pending': 'Avoinna',
    'ops.clients.invoiceHistory': 'Laskuhistoria',
    'ops.clients.visitHistory': 'Vierailuhistoria',
    'ops.clients.noVisits': 'Ei vierailuja',
    'ops.clients.addressPh': 'Katu ja numero',
    'visit.status.pending': 'Odottaa',
    'visit.status.follow_up': 'Seuranta',
    'visit.status.closed': 'Suljettu',
    'visit.status.lost': 'Menetetty',
    'ops.visits.title': 'Vierailujen CRM',
    'ops.visits.new': 'Uusi vierailu',
    'ops.visits.edit': 'Muokkaa vierailua',
    'ops.visits.save': 'Tallenna vierailu',
    'ops.visits.empty': 'Vierailuja ei löytynyt',
    'ops.visits.all': 'Kaikki',
    'ops.visits.prospectSection': 'Prospekti / yritys',
    'ops.visits.publicSearch': 'Hae toimipistettä julkisesta tietokannasta (Costa del Sol)',
    'ops.visits.publicSearchPh': 'Kirjoita nimestä vähintään 2 kirjainta...',
    'ops.visits.publicSearchHelp': 'Eikö ole tietokannassa? Jätä tämä kenttä tyhjäksi ja täytä tiedot käsin alla.',
    'ops.visits.publicVenue': 'Julkisen tietokannan toimipiste:',
    'ops.visits.changeVenue': 'Vaihda',
    'ops.visits.venueCompany': 'Toimipiste / yritys',
    'ops.visits.detailsSection': 'Vierailun tiedot',
    'ops.visits.existingClient': 'Olemassa oleva asiakas (valinnainen — vain lisämyyntivierailuille)',
    'ops.visits.newProspect': '— Prospekti (uusi) —',
    'ops.visits.clientSearchPh': 'Hae asiakasta...',
    'ops.visits.selectPlan': 'Valitse paketti...',
    'ops.visits.proposalSent': 'Ehdotus lähetetty',
    'ops.visits.followUpDate': 'Seurantapäivä',
    'ops.visits.nextAction': 'Seuraava toimenpide',
    'ops.visits.visitDate': 'Vierailu',
    'ops.visits.followUp': 'Seuranta',
    'ops.visits.client': 'Asiakas',
    'ops.visits.fieldTitle': 'Rekisteröity PulseFieldissä',
    'ops.visits.convertToClient': 'Muunna asiakkaaksi',
    'ops.visits.converting': 'Muunnetaan...',
    'ops.visits.convertError': 'Asiakkaaksi muunto epäonnistui',
    'ops.visits.clientCreated': 'Asiakas "{name}" luotu. Siirry Laskut-osioon luodaksesi ensimmäisen laskun.',
    'ops.cash.title': 'Kassa',
    'ops.cash.income': 'Tulo',
    'ops.cash.expense': 'Kulu',
    'ops.cash.newIncome': 'Uusi tulo',
    'ops.cash.newExpense': 'Uusi kulu',
    'ops.cash.addIncome': 'Lisää tulo',
    'ops.cash.addExpense': 'Lisää kulu',
    'ops.cash.concept': 'Selite',
    'ops.cash.conceptIncomePh': 'esim. La Bahian kuukausitilaus',
    'ops.cash.conceptExpensePh': 'esim. Hostinger VPS -hosting',
    'ops.cash.amount': 'Summa',
    'ops.cash.category': 'Kategoria',
    'ops.cash.select': 'Valitse...',
    'ops.cash.vatType': 'ALV-tyyppi',
    'ops.cash.vatNormal': 'Normaali (ALV mukana)',
    'ops.cash.vatReverse': 'Käännetty verovelvollisuus (EU B2B)',
    'ops.cash.vatExempt': 'Vapaa ALV:sta',
    'ops.cash.vatRate': 'ALV-prosentti (%)',
    'ops.cash.linkInvoice': 'Linkitä laskuun (valinnainen)',
    'ops.cash.linkClient': 'Asiakas (valinnainen)',
    'ops.cash.noInvoice': 'Ei mitään',
    'ops.cash.noClient': 'Ei ketään',
    'ops.cash.invoiceSearchPh': 'Hae laskua...',
    'ops.cash.clientSearchPh': 'Hae asiakasta...',
    'ops.cash.recurring': 'Toistuva',
    'ops.cash.monthly': 'Kuukausittain',
    'ops.cash.quarterly': 'Neljännesvuosittain',
    'ops.cash.totalIncome': 'Tulot yhteensä',
    'ops.cash.totalExpenses': 'Kulut yhteensä',
    'ops.cash.noMovements': 'Liikkeitä ei vielä ole',
    'ops.cash.category.Invoice': 'Lasku',
    'ops.cash.category.Subscription': 'Tilaus',
    'ops.cash.category.Grant': 'Avustus',
    'ops.cash.category.Server': 'Palvelin',
    'ops.cash.category.Salary': 'Palkat',
    'ops.cash.category.Travel': 'Matkat',
    'ops.cash.category.Marketing': 'Markkinointi',
    'ops.cash.category.Legal': 'Lakiasiat',
    'ops.cash.category.Software': 'Ohjelmisto',
    'ops.cash.category.Office': 'Toimisto',
    'ops.cash.category.Other': 'Muu',
    'stage.new': 'Uusi',
    'stage.attempting_contact': 'Yhteydenotto',
    'stage.contacted': 'Otettu yhteyttä',
    'stage.interested': 'Kiinnostunut',
    'stage.demo_scheduled': 'Demo on sovittu',
    'stage.proposal_sent': 'Ehdotus lähetetty',
    'stage.negotiation': 'Neuvottelu',
    'stage.onboarding_pending': 'Käyttöönotto kesken',
    'stage.payment_pending': 'Maksu odottaa',
    'stage.active': 'Aktiivinen', 'stage.converted': 'Muunnettu',
    'stage.at_risk': 'Riskissä',
    'stage.churned': 'Poistunut',
    'stage.lost': 'Menetetty',
    'plan.premium_local': 'Premium Local',
    'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotellianalytiikka',
    'plan.hotel_elite': 'Elite-hotelli',
    'priority.urgent': 'Kiireellinen',
    'priority.high': 'Korkea',
    'priority.medium': 'Keskitaso',
    'priority.low': 'Matala',
    'activity.call': 'Puhelu',
    'activity.email': 'Sähköposti',
    'activity.visit': 'Vierailu',
    'activity.note': 'Huomautus',
    'activity.system': 'Järjestelmä',
    'reports.title': 'Raportit',
    'reports.download': 'Lataa',
    'reports.type': 'Raportin tyyppi',
    'reports.period': 'Ajanjakso',
    'reports.today': 'Tänään',
    'reports.week': 'Tällä viikolla',
    'reports.month': 'Tässä kuussa',
    'reports.quarter': 'Neljännesvuosi',
    'reports.year': 'Tänä vuonna',
    'reports.custom': '📅 Räätälöity',
    'reports.pdf': '⬇ PDF',
    'reports.excel': '⬇ Excel',
    'report.executive': '📋 Tiivistelmä',
    'report.pipeline': '⬡ Myyntiputki ja konversio',
    'report.activity': '↺ Liiketoiminta',
    'report.leads': '◎ Liidit ja prospektointi',
    'report.billing': '€ Liikevaihto ja MRR',
    'report.agents': '👤 Suoritus myyjittäin',
    'lead.new': 'Uusi liidi',
    'lead.name': 'Ravintolan / hotellin nimi',
    'lead.phone': 'Yhteysnumero',
    'ops.loading': 'Ladataan...',
    'ops.title': 'OPS-hallintapaneeli',
    'ops.allTime': 'Kaikki',
    'ops.thisMonth': 'Tässä kuussa',
    'ops.lastMonth': 'Edellinen kuukausi',
    'ops.thisYear': 'Tänä vuonna',
    'ops.resetData': 'Tietojen nollaus',
    'ops.collected': 'Maksettu',
    'ops.outstanding': 'Avoinna',
    'ops.cashBalance': 'Kassan saldo',
    'ops.forecast': '30 päivän ennuste',
    'ops.overdueInvoices': 'Erääntyneet laskut',
    'ops.daysOverdue': 'erääntyneet',
    'ops.vatReport': 'Arvonlisäveroraportti',
    'ops.outputVat': 'laskutettu arvonlisävero',
    'ops.inputVat': 'maksettu arvonlisävero',
    'ops.netVat': 'Maksettava netto-arvonlisävero',
    'ops.recentCash': 'Viimeisimmät muutokset',
    'ops.noMovements': 'Ei liikkeitä',
    'ops.latestInvoices': 'Viimeisimmät laskut',
    'ops.noInvoices': 'Ilman laskuja',
    'ops.invoiceNumber': 'Numero',
    'ops.invoiceDue': 'Eräpäivä',
    'ops.clientName': 'Asiakas',
    'ops.date': 'Päivämäärä',
    'ops.total': 'Yhteensä',
    'ops.status': 'Tila',
    'invoice.new': 'Uusi lasku',
    'invoice.create': 'Luo lasku',
    'invoice.number': 'Laskunumero',
    'invoice.selectClient': 'Valitse asiakas…',
    'invoice.searchClient': 'Hae asiakasta…',
    'invoice.issueDate': 'Laskun päiväys',
    'invoice.dueDate': 'Eräpäivä',
    'invoice.dueShort': 'Erääntyy',
    'invoice.paymentMethod': 'Maksutapa',
    'invoice.payment.bankTransfer': 'Pankkisiirto',
    'invoice.payment.cash': 'Käteinen',
    'invoice.type.normal': 'Normaali',
    'invoice.type.recurring': 'Toistuva',
    'invoice.interval': 'Väli',
    'invoice.interval.monthly': 'Kuukausittain',
    'invoice.interval.quarterly': 'Neljännesvuosittain',
    'invoice.vatJurisdiction': 'ALV-alue',
    'invoice.vatRateFor': 'ALV-kanta · {jurisdiction} (%)',
    'invoice.jurisdiction.estonia': 'Viro',
    'invoice.jurisdiction.spain': 'Espanja',
    'invoice.jurisdiction.eu': 'EU',
    'invoice.jurisdiction.exento': 'Vapautettu',
    'invoice.reverseTitle': 'Käännetty verovelvollisuus (art. 44)',
    'invoice.reverseHelp': 'ALV = 0 %. Asiakkaan VAT-numero vaaditaan. Lakiteksti näkyy PDF-laskussa.',
    'invoice.missingVatWarning': 'Tällä asiakkaalla ei ole VAT-numeroa. Lisää se Asiakkaat-osiossa ennen laskun lähettämistä.',
    'invoice.lines': 'Rivit',
    'invoice.description': 'Kuvaus',
    'invoice.qty': 'Määrä',
    'invoice.unitPrice': 'Yksikköhinta',
    'invoice.amount': 'Summa',
    'invoice.serviceDescription': 'Palvelun kuvaus',
    'invoice.addLine': '+ Lisää rivi',
    'invoice.taxableBase': 'Veroton summa',
    'invoice.vatType': 'ALV-tyyppi',
    'invoice.vat.normal': 'ALV',
    'invoice.vat.normalRate': 'ALV {rate}%',
    'invoice.vat.reverseShort': 'Käännetty ALV',
    'invoice.vat.exempt': 'Vapautettu',
    'invoice.notesPh': 'Sisäiset muistiinpanot tai lisätiedot',
    'invoice.error.selectClient': 'Valitse asiakas',
    'invoice.detailTitle': 'Lasku {number}',
    'invoice.issueDue': 'Päiväys / eräpäivä',
    'invoice.noDueDate': 'Ei eräpäivää',
    'invoice.paymentLink': 'Maksulinkki',
    'invoice.generatePaymentLink': 'Luo maksulinkki (Revolut)',
    'invoice.markSent': 'Merkitse lähetetyksi',
    'invoice.markPaid': 'Merkitse maksetuksi → lisää Kassaan',
    'invoice.cancelInvoice': 'Mitätöi',
    'invoice.downloadPdf': 'Lataa PDF',
    'invoice.verifactu.testMode': 'testitila · ei aktiivinen',
    'invoice.verifactu.help': 'Luo ketjutettu tietue (SHA-256-sormenjälki) ja AEAT-tarkistus-QR. Tämä ei ole aktiivinen vaatimustenmukaisuus ennen AEAT-rekisteröintiä ja vastuuilmoitusta.',
    'invoice.verifactu.generating': 'Luodaan…',
    'invoice.verifactu.generate': 'Luo Verifactu-tietue',
    'invoice.verifactu.qrAlt': 'Verifactu-QR',
    'invoice.verifactu.hash': 'Sormenjälki',
    'invoice.verifactu.previous': 'Ketjutettu kohteeseen',
    'invoice.verifactu.first': '(ensimmäinen tietue)',
    'invoice.status.draft': 'Luonnos',
    'invoice.status.sent': 'Lähetetty',
    'invoice.status.paid': 'Maksettu',
    'invoice.status.overdue': 'Erääntynyt',
    'invoice.status.cancelled': 'Mitätöity',
    'timelog.locationUnavailable': 'Sijainti ei ole saatavilla — leimaus tallennetaan ilman GPS:ää',
    'timelog.worker': 'Työntekijä',
    'timelog.clockIn': 'Sisään',
    'timelog.clockOut': 'Ulos',
    'timelog.hours': 'Tunnit',
    'timelog.entryLocation': 'Sisäänleimauksen sijainti',
    'timelog.sheetName': 'Työajan seuranta',
    'timelog.activeSince': 'Työvuoro aktiivinen alkaen {time}',
    'timelog.noActiveShift': 'Ei aktiivista työvuoroa',
    'timelog.clockingIn': 'Leimataan sisään...',
    'timelog.clockInAction': 'Leimaa sisään',
    'timelog.clockingOut': 'Leimataan ulos...',
    'timelog.clockOutAction': 'Leimaa ulos',
    'timelog.shiftCount': '{count} työvuoroa',
    'timelog.duration': 'Kesto',
    'timelog.location': 'Sijainti',
    'timelog.empty': 'Ei vielä kirjauksia',
    'timelog.active': 'Aktiivinen',
    'ops.nav.section': 'OPS — Talous',
    'ops.nav.dashboard': 'OPS-hallintapaneeli',
    'ops.nav.invoices': 'Laskut',
    'ops.nav.cash': 'Kassa',
    'ops.nav.timelog': 'Työajan seuranta',
    'ops.nav.clients': 'OPS-asiakkaat',
    'ops.nav.visits': 'Vierailut',
    'ops.nav.venues': 'Toimipisteet',
    'ops.nav.ai': 'OPS-tekoälyavustaja', 'ops.nav.books': 'Kirjanpito', 'ops.nav.bank': 'Pankki', 'ops.nav.tax': 'Verotus',
    'tax.title': 'Verotus ja sovellettava lainsäädäntö',
    'tax.subtitle': 'Sisäinen viite Novitum/PulseCostalle: vain velvoitteet, jotka voivat koskea sisäistä toimintaa tai B2B/B2C-palveluita. Vahvista aina kirjanpitäjältä ennen ilmoituksia.',
    'tax.defaultCountry': 'Verotuksellinen pohja',
    'tax.operatingScope': 'Laajuus',
    'tax.scopeText': 'Virolainen OÜ, ohjelmisto-/tekoälypalvelut, kansainväliset B2B/B2C-asiakkaat',
    'tax.warningTitle': 'Ei oletuksena',
    'tax.warningText': 'Espanjan ALV, Suomi tai UK vain jos kirjanpitäjä vahvistaa rekisteröinnin, toimipaikan tai paikalliset kuluttajavelvoitteet.',
    'tax.internal': 'Sisäinen toiminta',
    'tax.services': 'B2B/B2C-palvelut',
    'tax.form': 'Lomake / ilmoitus',
    'tax.applies': 'Soveltuvuus',
    'tax.cadence': 'Aikataulu',
    'tax.scope': 'Laajuus',
    'tax.note': 'Kirjanpidon huomio',
    'tax.applies.yes': 'Soveltuu',
    'tax.applies.conditional': 'Tarvittaessa',
    'tax.applies.watch': 'Seurattava',
    'venues.title': 'Toimipisteet (Costa del Sol)',
    'venues.subtitle': 'toimipistettä järjestelmässä — myyntikohteet',
    'venues.searchPh': 'Hae nimen tai osoitteen perusteella…',
    'venues.allCategories': 'Kaikki kategoriat',
    'venues.unclaimed': 'Vaatimatta',
    'venues.unvisited': 'Käymättä',
    'venues.category': 'Luokka',
    'venues.premium': 'Premium',
    'venues.claimed': 'Vaadittu',
    'venues.cold': 'Kylmä',
    'venues.prev': 'Edellinen',
    'venues.next': 'Seuraava',
    'venues.page': 'Sivu',
    'venues.of': '/',
    'venues.empty': 'Ei tuloksia',
    'campaign.audience': 'Yleisö',
    'campaign.copyCsv': 'Kopioi CSV',
    'campaign.channel': 'Kanava',
    'campaign.leads': 'Liidit',
    'campaign.accounts': 'Asiakkuudet',
    'campaign.venues': 'Toimipisteet',
    'campaign.manual': 'Manuaalinen',
    'campaign.loadingContacts': 'ladataan kontakteja',
    'campaign.selectedWithChannel': '{count} valittu · {channel}',
    'campaign.allZones': 'Kaikki alueet',
    'campaign.allCategories': 'Kaikki kategoriat',
    'campaign.addManual': 'Lisää kontakti käsin',
    'campaign.addManualHelp': 'Puuttuvalle toimipisteelle tai nopeaan testiin.',
    'campaign.namePh': 'Toimipisteen nimi',
    'campaign.add': 'Lisää',
    'campaign.message': 'Viesti',
    'campaign.copy': 'Kopioi',
    'campaign.subject': 'Aihe',
    'campaign.text': 'Teksti',
    'campaign.preview': 'Esikatselu',
    'campaign.recipients': 'Vastaanottajat',
    'campaign.showing': 'Näytetään {shown}/{total}',
    'campaign.unselectShown': 'Poista näytetyt',
    'campaign.selectShown': 'Valitse näytetyt',
    'campaign.clearAll': 'Tyhjennä kaikki',
    'campaign.selectFiltered': 'Valitse suodatetut',
    'campaign.searchPh': 'Hae nimellä, alueella tai kontaktilla',
    'campaign.assisted': 'Avustettu lähetys',
    'campaign.assistedHelp': 'Valitse kontaktit ja käsittele ne yksi kerrallaan.',
    'campaign.reviewed': '{done}/{total} tarkistettu',
    'campaign.start': 'Aloita',
    'campaign.reviewedTitle': 'Kampanja tarkistettu',
    'campaign.sentSkipped': '{sent} lähetetty · {skipped} ohitettu',
    'campaign.open': 'Avaa',
    'campaign.markSent': 'Merkitse lähetetyksi',
    'campaign.skip': 'Ohita',
    'campaign.restart': 'Aloita alusta',
    'campaign.emailBatches': 'Sähköpostierät',
    'campaign.emailBatchesHelp': 'Lähetä valitut BCC-kopioina 50 tai 60 vastaanottajan erissä.',
    'campaign.batchSize': 'Koko',
    'campaign.batchSummary': 'Erä {current}/{total} · {count} sähköpostia',
    'campaign.noEmailBatch': 'Valitse sähköpostillisia vastaanottajia erien luomiseksi.',
    'campaign.copyBatchEmails': 'Kopioi sähköpostit',
    'campaign.openBatch': 'Avaa erä',
    'campaign.sendBrevo': 'Lähetä Brevolla',
    'campaign.prevBatch': 'Edellinen',
    'campaign.nextBatch': 'Seuraava',
    'campaign.confirmBrevo': 'Olet lähettämässä tämän erän {count} sähköpostiin Brevon kautta. Jatketaanko?',
    'campaign.batchPersonalizationWarning': 'Erissä {nombre} korvataan yleisellä tervehdyksellä.',
    'campaign.loadingEmpty': 'Ladataan kontakteja...',
    'campaign.noContacts': 'Tälle kanavalle ei ole kontakteja.',
    'campaign.more': 'Näytä {count} lisää / {total}',
    'campaign.openEmail': 'Avaa sähköposti',
    'campaign.openWhatsapp': 'Avaa WhatsApp',
    'campaign.statusLoadError': 'Kontaktien lataus epäonnistui',
    'campaign.statusCsvCopied': '{count} kontaktia kopioitu CSV:nä',
    'campaign.statusSelectFirst': 'Valitse vastaanottajat ennen kampanjan aloittamista',
    'campaign.statusPrepared': 'Kampanja valmis: {count} vastaanottajaa',
    'campaign.statusReviewed': 'Kampanja tarkistettu: {sent} lähetetty, {skipped} ohitettu',
    'campaign.statusManualMissing': 'Lisää nimi ja vähintään sähköposti tai puhelin',
    'campaign.statusManualAdded': '{name} lisätty käsin',
    'campaign.statusMessageCopied': 'Viesti kopioitu',
    'campaign.statusBatchEmailsCopied': 'Erän sähköpostit kopioitu',
    'campaign.statusBrevoSent': 'Erä lähetetty Brevolla {count} vastaanottajalle',
    'campaign.sourceAccount': 'Asiakkuus · {value}',
    'campaign.sourceVenue': 'Toimipiste · {value}',
    'campaign.sourceVenueNoCategory': 'Ei kategoriaa',
    'campaign.sourceLead': 'Liidi · {value}',
    'campaign.sourceManual': 'Manuaalinen',
    'category.bar': 'Baari',
    'category.hotel': 'Hotelli',
    'category.restaurant': 'Ravintola',
    'category.nightclub': 'Yökerho',
    'category.beach_club': 'Rantaklubi',
    'category.wellness': 'Hyvinvointi',
    'category.other': 'Muu',
    'campaign.template.email.subject': 'PulseCosta: paikallinen näkyvyys Costa del Solilla',
    'campaign.template.email.body': 'Hei {nombre},\n\nOlen Cipriano PulseCostalta. Valmistelemme paikallista kampanjaa, joka antaa Costa del Solin yrityksille enemmän näkyvyyttä ajantasaisilla aukioloajoilla, kuvilla ja yhteystiedoilla.\n\nSopiiko, että tarkistamme tietonne ja laitamme profiilin kuntoon tällä viikolla?\n\nKiitos,\nPulseCosta',
    'campaign.template.whatsapp.subject': '',
    'campaign.template.whatsapp.body': 'Hei {nombre}, olen Cipriano PulseCostalta. Päivitämme Costa del Solin yritysprofiileja, jotta näkyvyys, aukioloajat ja kuvat ovat ajan tasalla. Sopiiko, että tarkistamme teidän profiilinne tällä viikolla?',
  },
  et: {
    'sec.main': 'Avaleht',
    'sec.prospecting': 'Müük',
    'sec.ops': 'Operatiivne',
    'sec.analytics': 'Analüüs',
    'nav.dashboard': 'Juhtpaneel',
    'nav.pipeline': 'Müügitoru',
    'nav.leads': 'Potentsiaalsed kliendid',
    'nav.accounts': 'Kontod',
    'nav.tasks': 'Ülesanded',
    'nav.activities': 'Tegevused',
    'nav.reports': 'Aruanded',
    'nav.campaigns': 'Kampaaniad',
    'btn.newLead': '+ Uus potentsiaalne klient',
    'btn.newAccount': '+ Uus konto',
    'btn.export': 'Ekspordi CSV',
    'btn.signin': 'Logi sisse',
    'btn.save': 'Salvesta',
    'btn.cancel': 'Tühista',
    'btn.edit': 'Muuda',
    'common.yes': 'Jah',
    'common.no': 'Ei',
    'filter.allZones': 'Kõik piirkonnad',
    'filter.allPlans': 'Kõik paketid',
    'filter.allSources': 'Kõik allikad',
    'filter.allStatuses': 'Kõik olekud',
    'filter.allAgents': 'Kõik esindajad',
    'label.zone': 'Piirkond',
    'label.plan': 'Pakett',
    'label.stage': 'Etapp',
    'label.agent': 'Agent',
    'label.date': 'Kuupäev',
    'label.status': 'Olek',
    'label.priority': 'Prioriteet',
    'label.name': 'Nimi',
    'label.type': 'Tüüp',
    'label.source': 'Allikas',
    'label.mrr': 'MRR',
    'label.contact': 'Kontakt',
    'label.notes': 'Märkused',
    'label.address': 'Aadress',
    'common.back': 'Tagasi',
    'dash.activeLeads': 'Aktiivsed potentsiaalsed kliendid',
    'dash.activeAccounts': 'Aktiivsed kontod',
    'dash.mrr': 'Hinnanguline MRR',
    'dash.overdue': 'Tähtaeg ületanud ülesanded',
    'dash.recentActivity': 'Viimased tegevused',
    'dash.priorityTasks': 'Esmatähtsad ülesanded',
    'dash.topPipeline': 'Top Pipeline',
    'common.seeAll': 'Vaata kõiki →',
    'common.today': 'Täna',
    'common.thisWeek': 'Sel nädalal',
    'common.thisMonth': 'Sel kuul',
    'common.search': 'Otsi...',
    'common.loading': 'Laadimine...',
    'common.email': 'E-post',
    'common.phone': 'Telefon',
    'common.password': 'Parool',
    'common.saving': 'Salvestamine...',
    'common.saveError': 'Salvestamine ebaõnnestus',
    'common.brandBadge': 'Müügi CRM',
    'common.close': 'Sulge',
    'common.menuOpen': 'Ava menüü',
    'common.menuClose': 'Sulge menüü',
    'nav.assistant': 'Tehisintellekti abiline',
    'auth.signOut': 'Logi välja',
    'role.superAdmin': 'Peaadministraator',
    'app.installTitle': 'Installi rakendus',
    'app.installInstructions': 'Installi PulseCosta CRM\n\niOS Safari → Jaga → Lisa avalehele\nAndroid/Chrome → Menüü ⋮ → Installi rakendus\nChrome desktop → Menüü ⋮ → Installi rakendus',
    'login.subtitle': 'CRM · Müügipaneel',
    'login.passwordRequired': 'Sisesta parool',
    'login.invalidCredentials': 'Valed sisselogimisandmed',
    'login.showPassword': 'Näita parooli',
    'login.hidePassword': 'Peida parool',
    'login.footer': 'Fuengirola · Marbella · Estepona · Costa del Sol',
    'placeholder.initialNotes': 'Algmärkused...',
    'placeholder.contactName': 'Kontaktisiku nimi',
    'placeholder.taskTitle': 'Helista Hotel Bahiale',
    'placeholder.activityDescription': 'Kirjelda tegevust...',
    'type.local': 'Ettevõte / Baar / Restoran',
    'type.hotel': 'Hotell',
    'lead.convertConfirm': 'Kas muuta "{name}" müügitoru kontoks?',
    'lead.convertError': 'Teisendamine ebaõnnestus',
    'lead.converting': 'Teisendamine...',
    'lead.convertToAccount': 'Muuda kontoks',
    'lead.call': 'Helista',
    'lead.originNote': 'Päritolu: liid #{id}{source}',
    'assistant.summary': 'Päeva kokkuvõte',
    'assistant.visits': 'Külastuste analüüs',
    'assistant.ask': 'Küsi',
    'assistant.subtitle': 'Kohalik tehisintellekt (Spark) · PulseCosta CRM',
    'assistant.generate': 'Loo',
    'assistant.empty': 'Vali režiim ja loo esimene analüüs.',
    'assistant.loading': 'Analüüsin kohaliku tehisintellektiga (Spark)...',
    'assistant.questionPh': 'Küsi midagi CRM-i kohta...',
    'assistant.send': 'Saada',
    'assistant.clear': 'Tühjenda vestlus',
    'account.notFound': 'Kontot ei leitud.',
    'account.overview': 'Ülevaade',
    'account.contractDetails': 'Lepingu üksikasjad',
    'account.perMonth': 'kuu',
    'account.perYear': 'aasta',
    'account.annualMrr': 'Aastane MRR',
    'account.createdAt': 'Loodud',
    'account.updatedAt': 'Viimane uuendus',
    'account.noActivity': 'Tegevusi pole registreeritud.',
    'account.tasksHelp': 'Selle kontoga seotud ülesandeid hallatakse jaotises Ülesanded.',
    'label.companyName': 'Ettevõte / nimi',
    'label.contactPerson': 'Kontaktisik',
    'label.postalCode': 'Postiindeks',
    'label.city': 'Linn',
    'label.country': 'Riik',
    'ops.clients.title': 'Kliendid',
    'ops.clients.new': 'Uus klient',
    'ops.clients.edit': 'Muuda klienti',
    'ops.clients.save': 'Salvesta klient',
    'ops.clients.searchPh': 'Otsi nime, linna või maksu-/VAT-numbri järgi...',
    'ops.clients.empty': 'Kliente ei leitud',
    'ops.clients.pending': 'Ootel',
    'ops.clients.invoiceHistory': 'Arvete ajalugu',
    'ops.clients.visitHistory': 'Külastuste ajalugu',
    'ops.clients.noVisits': 'Külastusi pole',
    'ops.clients.addressPh': 'Tänav ja number',
    'visit.status.pending': 'Ootel',
    'visit.status.follow_up': 'Järeltegevus',
    'visit.status.closed': 'Suletud',
    'visit.status.lost': 'Kaotatud',
    'ops.visits.title': 'Külastuste CRM',
    'ops.visits.new': 'Uus külastus',
    'ops.visits.edit': 'Muuda külastust',
    'ops.visits.save': 'Salvesta külastus',
    'ops.visits.empty': 'Külastusi ei leitud',
    'ops.visits.all': 'Kõik',
    'ops.visits.prospectSection': 'Potentsiaalne klient / ettevõte',
    'ops.visits.publicSearch': 'Otsi ettevõtet avalikust andmebaasist (Costa del Sol)',
    'ops.visits.publicSearchPh': 'Sisesta nimest vähemalt 2 tähte...',
    'ops.visits.publicSearchHelp': 'Kas pole andmebaasis? Jäta see väli tühjaks ja täida all käsitsi vaba prospektina.',
    'ops.visits.publicVenue': 'Avaliku andmebaasi ettevõte:',
    'ops.visits.changeVenue': 'Muuda',
    'ops.visits.venueCompany': 'Ettevõte / firma',
    'ops.visits.detailsSection': 'Külastuse üksikasjad',
    'ops.visits.existingClient': 'Olemasolev klient (valikuline — ainult lisamüügi külastustele)',
    'ops.visits.newProspect': '— Prospekt (uus) —',
    'ops.visits.clientSearchPh': 'Otsi klienti...',
    'ops.visits.selectPlan': 'Vali pakett...',
    'ops.visits.proposalSent': 'Pakkumine saadetud',
    'ops.visits.followUpDate': 'Järeltegevuse kuupäev',
    'ops.visits.nextAction': 'Järgmine tegevus',
    'ops.visits.visitDate': 'Külastus',
    'ops.visits.followUp': 'Järeltegevus',
    'ops.visits.client': 'Klient',
    'ops.visits.fieldTitle': 'Registreeritud PulseFieldis',
    'ops.visits.convertToClient': 'Muuda kliendiks',
    'ops.visits.converting': 'Teisendamine...',
    'ops.visits.convertError': 'Kliendiks teisendamine ebaõnnestus',
    'ops.visits.clientCreated': 'Klient "{name}" loodud. Esimese arve loomiseks mine jaotisesse Arved.',
    'ops.cash.title': 'Kassa',
    'ops.cash.income': 'Tulu',
    'ops.cash.expense': 'Kulu',
    'ops.cash.newIncome': 'Uus tulu',
    'ops.cash.newExpense': 'Uus kulu',
    'ops.cash.addIncome': 'Lisa tulu',
    'ops.cash.addExpense': 'Lisa kulu',
    'ops.cash.concept': 'Selgitus',
    'ops.cash.conceptIncomePh': 'nt La Bahia kuutellimus',
    'ops.cash.conceptExpensePh': 'nt Hostinger VPS majutus',
    'ops.cash.amount': 'Summa',
    'ops.cash.category': 'Kategooria',
    'ops.cash.select': 'Vali...',
    'ops.cash.vatType': 'Käibemaksu tüüp',
    'ops.cash.vatNormal': 'Tavaline (käibemaksuga)',
    'ops.cash.vatReverse': 'Pöördmaksustamine (EL B2B)',
    'ops.cash.vatExempt': 'Maksuvaba',
    'ops.cash.vatRate': 'Käibemaksu määr (%)',
    'ops.cash.linkInvoice': 'Seo arvega (valikuline)',
    'ops.cash.linkClient': 'Klient (valikuline)',
    'ops.cash.noInvoice': 'Puudub',
    'ops.cash.noClient': 'Puudub',
    'ops.cash.invoiceSearchPh': 'Otsi arvet...',
    'ops.cash.clientSearchPh': 'Otsi klienti...',
    'ops.cash.recurring': 'Korduv',
    'ops.cash.monthly': 'Igakuine',
    'ops.cash.quarterly': 'Kvartaalne',
    'ops.cash.totalIncome': 'Tulud kokku',
    'ops.cash.totalExpenses': 'Kulud kokku',
    'ops.cash.noMovements': 'Liikumisi pole veel',
    'ops.cash.category.Invoice': 'Arve',
    'ops.cash.category.Subscription': 'Tellimus',
    'ops.cash.category.Grant': 'Toetus',
    'ops.cash.category.Server': 'Server',
    'ops.cash.category.Salary': 'Palgad',
    'ops.cash.category.Travel': 'Reisimine',
    'ops.cash.category.Marketing': 'Turundus',
    'ops.cash.category.Legal': 'Õigus',
    'ops.cash.category.Software': 'Tarkvara',
    'ops.cash.category.Office': 'Kontor',
    'ops.cash.category.Other': 'Muu',
    'stage.new': 'Uus',
    'stage.attempting_contact': 'Kontakti loomine',
    'stage.contacted': 'Võeti ühendust',
    'stage.interested': 'Huvitatud',
    'stage.demo_scheduled': 'Demo on kavandatud',
    'stage.proposal_sent': 'Ettepanek on saadetud',
    'stage.negotiation': 'Läbirääkimised',
    'stage.onboarding_pending': 'Kasutuselevõtt ootel',
    'stage.payment_pending': 'Makse ootel',
    'stage.active': 'Aktiivne', 'stage.converted': 'Konverteeritud',
    'stage.at_risk': 'Riskis',
    'stage.churned': 'Lahkunud',
    'stage.lost': 'Kaotatud',
    'plan.premium_local': 'Premium Local',
    'plan.pro_bi': 'Pro BI',
    'plan.hotel_analytics': 'Hotellianalüütika',
    'plan.hotel_elite': 'Hotell Elite',
    'priority.urgent': 'Kiire',
    'priority.high': 'Kõrge',
    'priority.medium': 'Keskmine',
    'priority.low': 'Madal',
    'activity.call': 'Kõne',
    'activity.email': 'E-post',
    'activity.visit': 'Külastus',
    'activity.note': 'Märkus',
    'activity.system': 'Süsteem',
    'reports.title': 'Aruanded',
    'reports.download': 'Laadi alla',
    'reports.type': 'Aruande liik',
    'reports.period': 'Ajavahemik',
    'reports.today': 'Täna',
    'reports.week': 'Sel nädalal',
    'reports.month': 'Sel kuul',
    'reports.quarter': 'Kvartal',
    'reports.year': 'Sel aastal',
    'reports.custom': '📅 Kohandatud',
    'reports.pdf': '⬇ PDF',
    'reports.excel': '⬇ Excel',
    'report.executive': '📋 Kokkuvõte',
    'report.pipeline': '⬡ Müügitoru ja konversioon',
    'report.activity': '↺ Müügitegevus',
    'report.leads': '◎ Potentsiaalsed kliendid ja potentsiaalsete klientide otsimine',
    'report.billing': '€ Käive ja MRR',
    'report.agents': '👤 Tulemuslikkus töötaja kohta',
    'lead.new': 'Uus potentsiaalne klient',
    'lead.name': 'Asutuse / hotelli nimi',
    'lead.phone': 'Kontaktnumber',
    'ops.loading': 'Laadimine...',
    'ops.title': 'OPS-i juhtpaneel',
    'ops.allTime': 'Kõik',
    'ops.thisMonth': 'Sel kuul',
    'ops.lastMonth': 'Eelmine kuu',
    'ops.thisYear': 'Sel aastal',
    'ops.resetData': 'Lähtesta andmed',
    'ops.collected': 'Laekunud',
    'ops.outstanding': 'Ootel',
    'ops.cashBalance': 'Kassasaldo',
    'ops.forecast': '30-päevane prognoos',
    'ops.overdueInvoices': 'Tähtaegunud arved',
    'ops.daysOverdue': 'tähtaeg ületanud',
    'ops.vatReport': 'Käibemaksuaruanne',
    'ops.outputVat': 'Edasi arvestatud käibemaks',
    'ops.inputVat': 'Eelnevalt tasutud käibemaks',
    'ops.netVat': 'Tasumisele kuuluv neto-käibemaks',
    'ops.recentCash': 'Viimased muutused',
    'ops.noMovements': 'Liikumisteta',
    'ops.latestInvoices': 'Viimased arved',
    'ops.noInvoices': 'Ilma arveteta',
    'ops.invoiceNumber': 'Number',
    'ops.invoiceDue': 'Tähtaeg',
    'ops.clientName': 'Klient',
    'ops.date': 'Kuupäev',
    'ops.total': 'Kokku',
    'ops.status': 'Olek',
    'invoice.new': 'Uus arve',
    'invoice.create': 'Loo arve',
    'invoice.number': 'Arve number',
    'invoice.selectClient': 'Vali klient…',
    'invoice.searchClient': 'Otsi klienti…',
    'invoice.issueDate': 'Väljastamise kuupäev',
    'invoice.dueDate': 'Maksetähtaeg',
    'invoice.dueShort': 'Tähtaeg',
    'invoice.paymentMethod': 'Makseviis',
    'invoice.payment.bankTransfer': 'Pangaülekanne',
    'invoice.payment.cash': 'Sularaha',
    'invoice.type.normal': 'Tavaline',
    'invoice.type.recurring': 'Korduv',
    'invoice.interval': 'Intervall',
    'invoice.interval.monthly': 'Igakuine',
    'invoice.interval.quarterly': 'Kvartaalne',
    'invoice.vatJurisdiction': 'Käibemaksu jurisdiktsioon',
    'invoice.vatRateFor': 'Käibemaksumäär · {jurisdiction} (%)',
    'invoice.jurisdiction.estonia': 'Eesti',
    'invoice.jurisdiction.spain': 'Hispaania',
    'invoice.jurisdiction.eu': 'EL',
    'invoice.jurisdiction.exento': 'Maksuvaba',
    'invoice.reverseTitle': 'Pöördmaksustamine (art. 44)',
    'invoice.reverseHelp': 'Käibemaks = 0%. Kliendi VAT-number on nõutav. Õiguslik märkus lisatakse PDF-arvele.',
    'invoice.missingVatWarning': 'Sellel kliendil puudub VAT-number. Lisa see Klientide jaotises enne arve väljastamist.',
    'invoice.lines': 'Read',
    'invoice.description': 'Kirjeldus',
    'invoice.qty': 'Kogus',
    'invoice.unitPrice': 'Ühiku hind',
    'invoice.amount': 'Summa',
    'invoice.serviceDescription': 'Teenuse kirjeldus',
    'invoice.addLine': '+ Lisa rida',
    'invoice.taxableBase': 'Maksustatav summa',
    'invoice.vatType': 'KM tüüp',
    'invoice.vat.normal': 'KM',
    'invoice.vat.normalRate': 'KM {rate}%',
    'invoice.vat.reverseShort': 'Pöördmaks',
    'invoice.vat.exempt': 'Maksuvaba',
    'invoice.notesPh': 'Sisemärkused või lisainfo',
    'invoice.error.selectClient': 'Vali klient',
    'invoice.detailTitle': 'Arve {number}',
    'invoice.issueDue': 'Väljastamine / tähtaeg',
    'invoice.noDueDate': 'Tähtaeg puudub',
    'invoice.paymentLink': 'Makselink',
    'invoice.generatePaymentLink': 'Loo makselink (Revolut)',
    'invoice.markSent': 'Märgi saadetuks',
    'invoice.markPaid': 'Märgi makstuks → lisa Kassasse',
    'invoice.cancelInvoice': 'Tühista',
    'invoice.downloadPdf': 'Laadi PDF alla',
    'invoice.verifactu.testMode': 'testrežiim · pole aktiivne',
    'invoice.verifactu.help': 'Loo aheldatud kirje (SHA-256 sõrmejälg) ja AEAT kontroll-QR. See ei ole aktiivne vastavus enne AEAT registreerimist ja vastutuskinnitust.',
    'invoice.verifactu.generating': 'Loomine…',
    'invoice.verifactu.generate': 'Loo Verifactu kirje',
    'invoice.verifactu.qrAlt': 'Verifactu QR',
    'invoice.verifactu.hash': 'Sõrmejälg',
    'invoice.verifactu.previous': 'Aheldatud kirjega',
    'invoice.verifactu.first': '(esimene kirje)',
    'invoice.status.draft': 'Mustand',
    'invoice.status.sent': 'Saadetud',
    'invoice.status.paid': 'Makstud',
    'invoice.status.overdue': 'Tähtaeg ületatud',
    'invoice.status.cancelled': 'Tühistatud',
    'timelog.locationUnavailable': 'Asukoht pole saadaval — tööaja kanne salvestatakse ilma GPS-ita',
    'timelog.worker': 'Töötaja',
    'timelog.clockIn': 'Sisenemine',
    'timelog.clockOut': 'Väljumine',
    'timelog.hours': 'Tunnid',
    'timelog.entryLocation': 'Sisenemise asukoht',
    'timelog.sheetName': 'Tööaja arvestus',
    'timelog.activeSince': 'Aktiivne töövahetus alates {time}',
    'timelog.noActiveShift': 'Aktiivset töövahetust pole',
    'timelog.clockingIn': 'Sisenemise märkimine...',
    'timelog.clockInAction': 'Märgi sisenemine',
    'timelog.clockingOut': 'Väljumise märkimine...',
    'timelog.clockOutAction': 'Märgi väljumine',
    'timelog.shiftCount': '{count} töövahetust',
    'timelog.duration': 'Kestus',
    'timelog.location': 'Asukoht',
    'timelog.empty': 'Kirjeid veel pole',
    'timelog.active': 'Aktiivne',
    'ops.nav.section': 'OPS — Rahandus',
    'ops.nav.dashboard': 'OPS-i juhtpaneel',
    'ops.nav.invoices': 'Arved',
    'ops.nav.cash': 'Kassa',
    'ops.nav.timelog': 'Tööaja arvestus',
    'ops.nav.clients': 'OPS-i kliendid',
    'ops.nav.visits': 'Külastused',
    'ops.nav.venues': 'Ettevõtted',
    'ops.nav.ai': 'OPS-i tehisintellekti abiline', 'ops.nav.books': 'Raamatupidamine', 'ops.nav.bank': 'Pank', 'ops.nav.tax': 'Maksud',
    'tax.title': 'Maksud ja kohaldatav õigus',
    'tax.subtitle': 'Sisemine viide Novitum/PulseCostale: ainult kohustused, mis võivad mõjutada sisemist tegevust või B2B/B2C teenuste osutamist. Enne deklaratsioonide esitamist kinnita alati raamatupidajaga.',
    'tax.defaultCountry': 'Maksubaas',
    'tax.operatingScope': 'Ulatus',
    'tax.scopeText': 'Eesti OÜ, tarkvara-/AI-teenused, rahvusvahelised B2B/B2C kliendid',
    'tax.warningTitle': 'Mitte vaikimisi kasutada',
    'tax.warningText': 'Hispaania käibemaks, Soome või UK ainult siis, kui raamatupidaja kinnitab registreeringu, püsiva tegevuskoha või kohaliku tarbija kohustuse.',
    'tax.internal': 'Sisemine tegevus',
    'tax.services': 'B2B/B2C teenused',
    'tax.form': 'Vorm / deklaratsioon',
    'tax.applies': 'Kohaldumine',
    'tax.cadence': 'Sagedus',
    'tax.scope': 'Ulatus',
    'tax.note': 'Märkus raamatupidajale',
    'tax.applies.yes': 'Kohaldub',
    'tax.applies.conditional': 'Kui asjakohane',
    'tax.applies.watch': 'Jälgi',
    'venues.title': 'Ettevõtted (Costa del Sol)',
    'venues.subtitle': 'ettevõtet süsteemis — potentsiaalsed kliendid',
    'venues.searchPh': 'Otsi nime või aadressi järgi…',
    'venues.allCategories': 'Kõik kategooriad',
    'venues.unclaimed': 'Nõudeta',
    'venues.unvisited': 'Külastamata',
    'venues.category': 'Kategooria',
    'venues.premium': 'Premium',
    'venues.claimed': 'Nõutud',
    'venues.cold': 'Külm',
    'venues.prev': 'Eelmine',
    'venues.next': 'Järgmine',
    'venues.page': 'Lehekülg',
    'venues.of': '/',
    'venues.empty': 'Tulemusi ei leitud',
    'campaign.audience': 'Sihtrühm',
    'campaign.copyCsv': 'Kopeeri CSV',
    'campaign.channel': 'Kanal',
    'campaign.leads': 'Liidid',
    'campaign.accounts': 'Kontod',
    'campaign.venues': 'Ettevõtted',
    'campaign.manual': 'Käsitsi',
    'campaign.loadingContacts': 'kontaktide laadimine',
    'campaign.selectedWithChannel': '{count} valitud · {channel}',
    'campaign.allZones': 'Kõik piirkonnad',
    'campaign.allCategories': 'Kõik kategooriad',
    'campaign.addManual': 'Lisa kontakt käsitsi',
    'campaign.addManualHelp': 'Puuduva ettevõtte või kiire testi jaoks.',
    'campaign.namePh': 'Ettevõtte nimi',
    'campaign.add': 'Lisa',
    'campaign.message': 'Sõnum',
    'campaign.copy': 'Kopeeri',
    'campaign.subject': 'Teema',
    'campaign.text': 'Tekst',
    'campaign.preview': 'Eelvaade',
    'campaign.recipients': 'Saajad',
    'campaign.showing': 'Kuvatakse {shown}/{total}',
    'campaign.unselectShown': 'Eemalda kuvatud',
    'campaign.selectShown': 'Vali kuvatud',
    'campaign.clearAll': 'Tühjenda kõik',
    'campaign.selectFiltered': 'Vali filtreeritud',
    'campaign.searchPh': 'Otsi nime, piirkonna või kontakti järgi',
    'campaign.assisted': 'Abistatud saatmine',
    'campaign.assistedHelp': 'Vali kontaktid ja tööta nendega ükshaaval.',
    'campaign.reviewed': '{done}/{total} üle vaadatud',
    'campaign.start': 'Alusta',
    'campaign.reviewedTitle': 'Kampaania üle vaadatud',
    'campaign.sentSkipped': '{sent} saadetud · {skipped} vahele jäetud',
    'campaign.open': 'Ava',
    'campaign.markSent': 'Märgi saadetuks',
    'campaign.skip': 'Jäta vahele',
    'campaign.restart': 'Alusta uuesti',
    'campaign.emailBatches': 'E-posti partiid',
    'campaign.emailBatchesHelp': 'Saada valitud kontaktidele BCC kaudu 50 või 60 kaupa.',
    'campaign.batchSize': 'Suurus',
    'campaign.batchSummary': 'Partii {current}/{total} · {count} e-posti',
    'campaign.noEmailBatch': 'Partiide loomiseks vali e-postiga saajad.',
    'campaign.copyBatchEmails': 'Kopeeri e-postid',
    'campaign.openBatch': 'Ava partii',
    'campaign.sendBrevo': 'Saada Brevoga',
    'campaign.prevBatch': 'Eelmine',
    'campaign.nextBatch': 'Järgmine',
    'campaign.confirmBrevo': 'Saadad selle partii Brevo kaudu {count} e-posti aadressile. Kas jätkata?',
    'campaign.batchPersonalizationWarning': 'Partiides asendatakse {nombre} üldise tervitusega.',
    'campaign.loadingEmpty': 'Kontaktide laadimine...',
    'campaign.noContacts': 'Selle kanali jaoks kontakte pole.',
    'campaign.more': 'Näita veel {count}/{total}',
    'campaign.openEmail': 'Ava e-post',
    'campaign.openWhatsapp': 'Ava WhatsApp',
    'campaign.statusLoadError': 'Kontaktide laadimine ebaõnnestus',
    'campaign.statusCsvCopied': '{count} kontakti kopeeritud CSV-na',
    'campaign.statusSelectFirst': 'Vali saajad enne kampaania alustamist',
    'campaign.statusPrepared': 'Kampaania valmis: {count} saajat',
    'campaign.statusReviewed': 'Kampaania üle vaadatud: {sent} saadetud, {skipped} vahele jäetud',
    'campaign.statusManualMissing': 'Lisa nimi ja vähemalt e-post või telefon',
    'campaign.statusManualAdded': '{name} lisatud käsitsi',
    'campaign.statusMessageCopied': 'Sõnum kopeeritud',
    'campaign.statusBatchEmailsCopied': 'Partii e-postid kopeeritud',
    'campaign.statusBrevoSent': 'Partii saadetud Brevo kaudu {count} saajale',
    'campaign.sourceAccount': 'Konto · {value}',
    'campaign.sourceVenue': 'Ettevõte · {value}',
    'campaign.sourceVenueNoCategory': 'Kategooriata',
    'campaign.sourceLead': 'Liid · {value}',
    'campaign.sourceManual': 'Käsitsi',
    'category.bar': 'Baar',
    'category.hotel': 'Hotell',
    'category.restaurant': 'Restoran',
    'category.nightclub': 'Ööklubi',
    'category.beach_club': 'Rannaklubi',
    'category.wellness': 'Heaolu',
    'category.other': 'Muu',
    'campaign.template.email.subject': 'PulseCosta: aktiveerime kohaliku nähtavuse Costa del Solis',
    'campaign.template.email.body': 'Tere {nombre},\n\nOlen Cipriano PulseCostast. Valmistame ette kohalikku kampaaniat, mis annab Costa del Soli ettevõtetele rohkem nähtavust ajakohaste lahtiolekuaegade, fotode ja kontaktandmetega.\n\nKas teile sobib, kui vaatame teie profiili üle ja teeme selle sel nädalal korda?\n\nAitäh,\nPulseCosta',
    'campaign.template.whatsapp.subject': '',
    'campaign.template.whatsapp.body': 'Tere {nombre}, olen Cipriano PulseCostast. Uuendame Costa del Soli ettevõtete profiile, et parandada nähtavust, lahtiolekuaegu ja fotosid. Kas teile sobib, kui vaatame teie profiili sel nädalal üle?',
  },

};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => {
      const saved = localStorage.getItem('crm_lang');
      return saved === 'es' || saved === 'en' || saved === 'fi' || saved === 'et' ? saved : 'es';
    }
  );

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('crm_lang', l);
  };

  const t = useCallback((key: string, vars?: Record<string, string | number>): string => {
    let text = (T[lang] ?? T.es)[key] ?? T.es[key] ?? key;
    if (vars) {
      for (const [name, value] of Object.entries(vars)) {
        text = text.replaceAll(`{${name}}`, String(value));
      }
    }
    return text;
  }, [lang]);
  // El <html lang> sigue al idioma elegido: evita que Chrome ofrezca traducir la app (y traduzca nombres de locales)
  useEffect(() => { document.documentElement.lang = lang; }, [lang]);

  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
}
